### ISSUE TITLE
All teleport plugins should log the identity of users approving / declining requests

### ISSUE THREAD

**Issue by fspmarshall** [gravitational/teleport-plugins#1]
The slackbot should log the identity of users when they approve or deny requests.

Once https://github.com/gravitational/teleport/issues/3204 has been resolved, user identity should be supplied to the Auth Server when setting request state.

**Comment by xnutsive** [comment]
@fspmarshall, one [half of this is done](https://github.com/gravitational/teleport-plugins/blob/7066422da9714f1d1f58dd40e99e6522cad19ae2/access/slackbot/main.go#L424). Not in an elegant way as of right now, but it does log who approved / denied a request on Slack. 

Let's keep this open until we can send the events to Teleport's audit log.

**Comment by xnutsive** [comment]
Here's how it currently looks after adding the structured logs: 

```
vm0:~/g/s/g/g/t/a/s/build sudo ./teleport-slackbot start --insecure-no-tls

INFO   Starting Teleport Access Slackbot 0.1.0-dev.1: slackbot/main.go:224
INFO   Starting a request watcher... slackbot/main.go:330
INFO   Starting insecure HTTP server on 0.0.0.0:8081 utils/http.go:64
INFO   Watcher connected slackbot/main.go:298
INFO   Slack user denied the request request_id:94b6ff7c-869e-47f5-a5b3-36f0b3a1e38b roles:[admin] slack_channel:gravitational slack_user:xnutsive user:parallels slackbot/main.go:409
INFO   Slack user approved the request request_id:9d54bb1a-a208-4c8f-81df-3d02c5bd1beb roles:[admin] slack_channel:gravitational slack_user:xnutsive user:parallels slackbot/main.go:409

```

**Comment by xnutsive** [comment]
I'm looking through all the issues today and keeping this open for now. @fspmarshall, any updates to the audit log on the teleport side?

**Comment by benarent** [comment]
Are we waiting on https://github.com/gravitational/teleport/issues/3204 @xnutsive ?

**Comment by fspmarshall** [comment]
@xnutsive @benarent, yeah I haven't gotten around to updating the audit log.  Been dealing with some teleport bug fixes which were higher priority (esp. since slackbot does log user locally).  I *should* have time to circle back to https://github.com/gravitational/teleport/issues/3204 later this week or early next week.

**Comment by benarent** [comment]
Just looping back on this request, I checked a pretty recently built master that should be #3204 in it and recently built from master for plugins.

Can you loop back and check the user identity should be supplied to the Auth Server when setting request state.

```json
{
  "code": "T5001I",
  "event": "access_request.update",
  "id": "aa841af8-db3f-4e33-9173-7089c3fa05e0",
  "state": "APPROVED",
  "time": "2020-05-15T17:49:19Z",
  "uid": "0fe4bf08-b004-4859-b8ab-37c0762ac1b7",
  "updated_by": "access-plugin"
}
```
