### ISSUE TITLE
`WaitForReady` should be configurable.

### ISSUE THREAD

**Issue by fspmarshall** [gravitational/teleport-plugins#102]
The `WaitForReady` option is always set to `true` for the GRPC client in `access/access.go`.  This ends up suppressing a lot of useful errors, making debug difficult.  We should make it configurable, and possibly off by default, in order to support an easier debug workflow.

**Comment by xnutsive** [comment]
@marshall-lee, would you have enough time until next week to also take on this one?

**Comment by xnutsive** [comment]
#128 pull request made it the default behavior in the grpc client to not set WaitForReady, but all of the plugins still use it from their code. 

The next step with this is to make sure the plugins stop using WaitForReady, and process any connection errors correctly.

**Comment by xnutsive** [comment]
@marshall-lee before I can continue with this — I need your input ;) Can you point me in the right direction as to where you're relying on WaitForReady behavior so I can test this / remove it / make it configurable?

**Comment by marshall-lee** [comment]
@fspmarshall wrote:

> Tough to say what the "right" thing to do is here, but my preference is to break existing behavior rather than keeping WaitForReady as true in the plugins. The WaitForReady option causes plugins to hang on errors which are clearly fatal (e.g. invalid certificates).

I'll re-visit this problem soon, need to figure out what's the impact it would be to disable this option completely.

As for invalid certificate problem: in plugins we mitigate it by manually checking the certificate expiration date — if it's expired we print the warning in the logs. Of course we cannot require the user of `access` package to do such checks too so we removed `WaitForReady(true)` from default parameters.

But I wonder what the other problems arise with this option?
