### ISSUE TITLE
Release 0.1.0 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#110]
As I've almost completed testing and docs, it seems like a good time to make a release without alpah/beta flag.

**Comment by webvictim** [comment]
Done.

https://get.gravitational.com/teleport-access-jira-v0.1.0-linux-amd64-bin.tar.gz
https://get.gravitational.com/teleport-access-mattermost-v0.1.0-linux-amd64-bin.tar.gz
https://get.gravitational.com/teleport-access-pagerduty-v0.1.0-linux-amd64-bin.tar.gz
https://get.gravitational.com/teleport-access-slack-v0.1.0-linux-amd64-bin.tar.gz
https://get.gravitational.com/teleport-access-gitlab-v0.1.0-linux-amd64-bin.tar.gz
