### ISSUE TITLE
Can't approve someone who is not on the schedule 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#114]
In this setup, I've created a user who's no rotation. I'm able to create a new incident but not approve it via PD. I would expect that the webhooks have been setup correct as the auto-approve worked. 

```
INFO   PagerDuty incident created pd_incident_id:PE19V0Q request_id:7f87614a-b185-499a-abb0-4262d542869a pagerduty/app.go:255
INFO   PagerDuty user approved the request pd_incident_id:PE19V0Q pd_user_email:ben@gravitational.com pd_user_name:Ben Arent request_id:7f87614a-b185-499a-abb0-4262d542869a pagerduty/app.go:305
INFO   Incident "PE19V0Q" has been resolved pd_incident_id:PE19V0Q pd_user_email:ben@gravitational.com pd_user_name:Ben Arent request_id:7f87614a-b185-499a-abb0-4262d542869a pagerduty/app.go:310
INFO   PagerDuty incident created pd_incident_id:P6Q6A2G request_id:0314b3a3-3f39-4ce8-8cc6-fc12402e0b8e pagerduty/app.go:255
```

![Screen Recording 2020-07-29 at 08 49 17 AM](https://user-images.githubusercontent.com/559288/88824671-81f94100-d17b-11ea-9f73-ee4cf0151ec2.gif)

**Comment by marshall-lee** [comment]
@benarent 

I believe it's due to misconfiguration of the plugin. Is `public_addr` setting correct? It's seems that plugin didn't receive the action an all, the most possible reason is that pagerduty sends its action to a wrong addr.

Tested your case on my cluster and everything works fine.

**Comment by xnutsive** [comment]
Also might be related: #120, #123.

**Comment by marshall-lee** [comment]
Closing as stale
Also, Pagerduty plugin doesn't have an approval through webhooks feature anymore
