### ISSUE TITLE
Provide alternative to `ngrok http`

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#12]
In the current implementation Forrest has been using `ngrok http` to proxy the requests from Slack.  We should provide this functionally natively within the plugin, and provide TLS support.

If the customer terminates at a load balancer with `--insecure-no-tls` https://gravitational.com/teleport/docs/cli-docs/#teleport-start 

```
# The DNS name the proxy HTTPS endpoint as accessible by cluster users.
# Defaults to the proxy's hostname if not specified. If running multiple
# proxies behind a load balancer, this name must point to the load balancer
# (see public_addr section below)
public_addr: proxy.example.com:3080

# TLS certificate for the HTTPS connection. Configuring these properly is
# critical for Teleport security.
https_key_file: /var/lib/teleport/webproxy_key.pem
https_cert_file: /var/lib/teleport/webproxy_cert.pem
```

**Comment by xnutsive** [comment]
Looks like our current implementation just listens as an http server and doesn't provide TLS support, right @marshall-lee? Sounds like just plugging TLS support + config entries shouldn't take long?

**Comment by xnutsive** [comment]
Discussed this with @benarent and @fspmarshall and decided: 

1. Slackbot should support TLS. 
2. Slackbot should have a `--insecure-no-tls` option that disables it, consistently with Teleport behavior.

**Comment by xnutsive** [comment]
I'll assign this to Sergey once he's in collaborators.

**Comment by xnutsive** [comment]
Reopening to keep this in front of our eyes until we add a default TLS configuration.
