### ISSUE TITLE
Teleport Plugins 0.1.0 Webhook doesn't seem to be working. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#120]
I have been testing with 0.1.0 and I'm having issues with the new webhook setup. 

```
DEBU   DEBUG logging enabled logrus/exported.go:117
INFO   Starting Teleport Access PagerDuty extension 0.1.0:teleport-pagerduty-v0.1.0-0-g22dc5d2 pagerduty/app.go:74
DEBU   Checking Teleport server version pagerduty/app.go:152
DEBU   Starting PagerDuty API health check... pagerduty/app.go:107
DEBU   PagerDuty API health check finished ok pagerduty/app.go:112
DEBU   Starting secure HTTPS server on 66.220.18.10:8883 utils/http.go:235
DEBU   Setting up the webhook extensions pagerduty/app.go:125
DEBU   PagerDuty webhook extensions setup finished ok pagerduty/app.go:130
DEBU   Watcher connected access/service_job.go:62
INFO   PagerDuty incident created pd_incident_id:PUZCFSH request_id:17aadf67-24bb-48d5-be8b-838015763a1b pagerduty/app.go:282
```
## PD Setup
It looks like the extensions might be incorrectly setup? 
![image](https://user-images.githubusercontent.com/559288/90052497-112f4a00-dc8e-11ea-97f2-45e0ccccf04a.png)

https://dev-teleport-test.pagerduty.com/service-directory/P4IC1VD/undefined?addonId=PZ5RU2P
![image](https://user-images.githubusercontent.com/559288/90052556-27d5a100-dc8e-11ea-8254-8f0393cbe094.png)

## Teleport Config File
```
 # example teleport-pagerduty configuration TOML file
[teleport]
auth_server = "teleport-ent-4-3.practice.io:3025"                            # Teleport Auth Server GRPC API address
client_key = "/var/lib/teleport/plugins/pagerduty/auth.key" # Teleport GRPC client secret key
client_crt = "/var/lib/teleport/plugins/pagerduty/auth.crt" # Teleport GRPC client certificate
root_cas = "/var/lib/teleport/plugins/pagerduty/auth.cas"   # Teleport cluster CA certs

[pagerduty]
api_key = "fzPbHPxxx"               # PagerDuty API Key
user_email = "ben@gravitational.com" # PagerDuty bot user email (Could be admin email)
service_id = "P4IC1VD"        # PagerDuty service id

[http]
public_addr = "https://teleport-ent-4-3.practice.io" # URL on which callback server is accessible externally, e.g. [https://]teleport-proxy.example.com
listen_addr = "teleport-ent-4-3.practice.io:8883" # Network address in format [addr]:port on which callback server listens, e.g. 0.0.0.0:8081
https_key_file = "/var/lib/teleport/webproxy_key.pem"  # TLS private key
https_cert_file = "/var/lib/teleport/webproxy_cert.pem" # TLS certificate

[http.tls]
verify_client_cert = true # The preferred way to authenticate webhooks on Pagerduty. See more: https://developer.pagerduty.com/docs/webhooks/webhooks-mutual-tls

#[http.basic_auth]
#user = "user"
#password = "password" # If you prefer to use basic auth for Pagerduty Webhooks authentication, use this section to store user and password

[log]
output = "stderr" # Logger output. Could be "stdout", "stderr" or "/var/lib/teleport/pagerduty.log"
severity = "INFO" # Logger severity. Could be "INFO", "ERROR", "DEBUG" or "WARN".
```

**Comment by xnutsive** [comment]
I'll run more tests tomorrow — @marshall-lee, please check this too and report back in the ticket. 

First glance, I suspect that `public_addr` doesn't contain the port number, and that might be an issue. I'm a bit confused by `public_addr` and `listen_addr`, but from what I gather, they work as follows: 

- `public_addr` is just a string that will be passed to the service (Pagerduty, in this case) as a `webhook_url` parameter, i.e. “please send your webhooks to this URL”. Whatever URL is passed here, the Teleport plugin should be accessible on this URL. Teleport plugin doesn't automatically append ports or anything else to it, it just uses it as is. 

- `listen_addr` is used internally for the http server to set the listen host and port. It's not passed to any 3rd party systems.

- Consider case 1:`listen_addr` is `:8883` (equivalent to `0.0.0.0:8083`, and `public_addr` is `https://teleport-ent-4-3.practice.io:8883` — then Pagerduty will hit the `public_addr` URL, and the plugin expects that you have your own reverse-proxy setup to route this request to the current server's `0.0.0.0:8083`, or simply the name is resolved to this host, and it's accessible publicly.

- Consider case 2: both `listen_addr` and `public_addr` are the same, `teleport-demo.cluster.respawn.icu:8883`. That would also work in case the server we run the plugin on knows it's public hostname is teleport-demo.cluster.respawn.icu.


I can do demos and test to reproduce this specific behavior you pointed out, and improve our docs (or fix the bug if there's a bug). 

Can you please try setting the port in public_addr and tell us if that works? @marshall-lee, WDYT, is that the port configuration?

**Comment by marshall-lee** [comment]
```
public_addr = "https://teleport-ent-4-3.practice.io" # URL on which callback server is accessible externally, e.g. [https://]teleport-proxy.example.com
listen_addr = "teleport-ent-4-3.practice.io:8883" # Network address in format [addr]:port on which callback server listens, e.g. 0.0.0.0:8081
```

Your plugin listens on 8883 but receives webhooks on 443 (you specified "https://" `public_addr` without a port). So either you route 443 -> 8883 with some reverse proxy, or change your `public_addr` to `https://teleport-ent-4-3.practice.io:8883`. Perhaps this will help:

```
public_addr = "https://teleport-ent-4-3.practice.io" # URL on which callback server is accessible externally, e.g. [https://]teleport-proxy.example.com
listen_addr = ":8883" # Network address in format [addr]:port on which callback server listens, e.g. 0.0.0.0:8081
```
