### ISSUE TITLE
Teleport starts with self signed cert 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#123]
![image](https://user-images.githubusercontent.com/559288/90183628-aef74780-dd68-11ea-9548-11e854bd09eb.png)

```
DEBU   Starting PagerDuty API health check... pagerduty/app.go:90
DEBU   PagerDuty API health check finished ok pagerduty/app.go:95
DEBU   Setting up the webhook extensions pagerduty/app.go:108
DEBU   Starting secure HTTPS server on [::]:8082 utils/http.go:235
DEBU   PagerDuty webhook extensions setup finished ok pagerduty/app.go:113
DEBU   Watcher connected access/service_job.go:62
```

**Comment by benarent** [comment]
@xnutsive @marshall-lee Something seems up with the webhook setup, I wonder if it's just related to TLS setup.

**Comment by xnutsive** [comment]
Can you please share the config you're using for Teleport, and for the plugin itself?

**Comment by benarent** [comment]
```
# example teleport-pagerduty configuration TOML file
[teleport]
auth_server = "teleport-ent-4-3.practice.io:3025"                            # Teleport Auth Server GRPC API address
client_key = "/var/lib/teleport/plugins/pagerduty/auth.key" # Teleport GRPC client secret key
client_crt = "/var/lib/teleport/plugins/pagerduty/auth.crt" # Teleport GRPC client certificate
root_cas = "/var/lib/teleport/plugins/pagerduty/auth.cas"   # Teleport cluster CA certs

[pagerduty]
api_key = "fzPbHPDQxxx"               # PagerDuty API Key
user_email = "ben@gravitational.com" # PagerDuty bot user email (Could be admin email)
service_id = "PGUI4RH"        # PagerDuty service id

[http]
public_addr = "https://teleport-ent-4-3.practice.io" # URL on which callback server is accessible externally, e.g. [https://]teleport-proxy.example.com
listen_addr = "0.0.0.0:8082" # Network address in format [addr]:port on which callback server listens, e.g. 0.0.0.0:8081
https_key_file = "/var/lib/teleport/webproxy_key.pem"  # TLS private key
https_cert_file = "/var/lib/teleport/webproxy_cert.pem" # TLS certificate

[http.tls]
verify_client_cert = true # The preferred way to authenticate webhooks on Pagerduty. See more: https://developer.pagerduty.com/docs/webhooks/webhooks-mutual-tls

#[http.basic_auth]
#user = "user"
#password = "password" # If you prefer to use basic auth for Pagerduty Webhooks authentication, use this section to store user and password

[log]
output = "stderr" # Logger output. Could be "stdout", "stderr" or "/var/lib/teleport/pagerduty.log"
severity = "INFO" # Logger severity. Could be "INFO", "ERROR", "DEBUG" or "WARN".
```


```
teleport5auth ~: sudo teleport-pagerduty start --config="/etc/teleport-pagerduty.toml"  --insecure-no-tls -d
DEBU   DEBUG logging enabled logrus/exported.go:117
INFO   Starting Teleport Access PagerDuty extension 0.2.0-dev:teleport-pagerduty-v0.1.0-alpha.3-25-g382b776 pagerduty/app.go:57
DEBU   Checking Teleport server version pagerduty/app.go:135
DEBU   Starting PagerDuty API health check... pagerduty/app.go:90
DEBU   PagerDuty API health check finished ok pagerduty/app.go:95
DEBU   Starting insecure HTTP server on [::]:8082 utils/http.go:232
DEBU   Setting up the webhook extensions pagerduty/app.go:108
```

**Comment by benarent** [comment]
I've tried with both secure / insecure and both don't seem to be working.

**Comment by xnutsive** [comment]
Thanks for the config! 

I assume that the server where you run the plugin has hostname `teleport-ent-4-3.practice.io`. If that's the case, than in your screenshot in the initial issue description, you navigate to `teleport-ent-4-3.practice.io:8882` in your browser, which resolves to the webhook listener of the `teleport-pagerduty`, which also has the tls authentication enabled. 

So it seems like it asks for the certificate to authenticate the webhook, which looks to be self-signed, am I following the problem correctly? 

If I understand how pagerduty webhook auth works, there are two certificate pairs in the plugin: 
1. First is just the standard TLS certificates for plugin's HTTP endpoint, i.e. HTTPS certs. 
2. Second pair is used to authenticate Pagerduty callbacks in the plugin, i.e. for user authentication, on top of standard HTTPS. 

I think that 2nd thing is generated automatically and can't be set to be a fixed certificate, wheres the first one should be. 

Let me know if this description helps, happy to rewrite / contribute to the documentation. Does this solve the problem, along with #120?

**Comment by marshall-lee** [comment]
@xnutsive 

> If I understand how pagerduty webhook auth works, there are two certificate pairs in the plugin

No it's not true, there's only one certificate/key pair for webhook endpoint, just like in other plugins.

`verify_client_cert = true` doesn't require any additional certificates *in the plugin*, this option just checks a pagerduty certificate used to invoke a webhook. This is done by verifying the `Subject` field of client certificate (client here is pagerduty itself).

**Comment by marshall-lee** [comment]
`/var/lib/teleport/webproxy_cert.pem` seems to be self-signed and I think it's the problem.

Provide a real certificate signed by CA for webhooks to work. PagerDuty refuses to send webhooks to such tls endpoints with self-signed certs cause it's insecure.

It's crucial because if you use self-signed cert for your teleport webproxy, you could just ignore the warning when accessing it in the browser. But there's no option to make PagerDuty ignore that your cert is self-signed.

**Comment by marshall-lee** [comment]
As for `--insecure-no-tls` option, it's only useful locally for development and it's also useful if your plugin sits behind the reverse proxy doing the TLS termination itself.

**Comment by benarent** [comment]
I figured it out,

I needed to add the port to public_addr and this works. I'm going to send in a PR to make the configure instructions clearer . 

```
[http]
public_addr = "https://teleport-ent-4-3.practice.io:8082" # URL on which callback server is accessible externally, e.g. [https://]teleport-proxy.example.com
listen_addr = "0.0.0.0:8082" 
```

**Comment by benarent** [comment]
It's odd, I tested this again https://teleport-ent-4-3.practice.io:8085/ and this webhook works, but still has the strange TLS error from the web. It's a minor issue,  I'm going to make the other configs more explicit.
