### ISSUE TITLE
Slack Auth/Scope missing_scope Issue

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport-plugins#134]
### Summary
The Slack Bot raises a missing_scope exception when detecting a new request has been created. 

```
ERRO   Failed to process pending request error:missing_scope request_id:b6015467-99eb-4de3-a8e0-fba96ceb334a slack/app.go:151
DEBU   "ERROR REPORT:  Original Error: *errors.errorString missing_scope
Stack Trace:    /go/src/github.com/gravitational/teleport-plugins/access/slack/bot.go:60 main.(*Bot).Post    
/go/src/github.com/gravitational/teleport-plugins/access/slack/app.go:264 main.(*App).onPendingRequest    
/go/src/github.com/gravitational/teleport-plugins/access/slack/app.go:148 main.(*App).onWatcherEvent    
/go/src/github.com/gravitational/teleport-plugins/access/service_job.go:71 github.com/gravitational/teleport-plugins/access.
(*watcherJob).eventLoop.func1
/go/src/github.com/gravitational/teleport-plugins/utils/process.go:187 github.com/gravitational/teleport-plugins/utils.jobFunc.DoJob
/go/src/github.com/gravitational/teleport-plugins/utils/process.go:82 github.com/gravitational/teleport-plugins/utils.NewProcess.func2.1
/usr/local/go/src/runtime/asm_amd64.s:1358 runtime.goexit
User Message: 
error:missing_scope request_id:b6015467-99eb-4de3-a8e0-fba96ceb334a slack/app.go:152

```

## Configuration

Per the [documentation](https://gravitational.com/teleport/docs/enterprise/workflow/ssh_approval_slack/), I set up a Slack bot , "CS-Teleport-Training", within the Slack [Applications Panel](https://api.slack.com/apps/). 

<img width="707" alt="Screen Shot 2020-08-28 at 8 20 48 PM" src="https://user-images.githubusercontent.com/241714/91625326-0f42d780-e96c-11ea-9008-0247ba96af9f.png">

Signing secret:
<img width="641" alt="Screen Shot 2020-08-28 at 8 22 17 PM" src="https://user-images.githubusercontent.com/241714/91625345-3699a480-e96c-11ea-954f-ed6eb7f2dfc5.png">

Scopes:
<img width="694" alt="Screen Shot 2020-08-28 at 8 24 52 PM" src="https://user-images.githubusercontent.com/241714/91625407-b58edd00-e96c-11ea-8d38-f13cefe1758a.png">

Webhook:
<img width="691" alt="Screen Shot 2020-08-28 at 8 24 39 PM" src="https://user-images.githubusercontent.com/241714/91625412-bcb5eb00-e96c-11ea-8bac-7d28123bb3d6.png">

Token:
<img width="661" alt="Screen Shot 2020-08-28 at 8 25 08 PM" src="https://user-images.githubusercontent.com/241714/91625420-c7708000-e96c-11ea-9dc6-257f5a83390a.png">

Config:
```
# example slack plugin configuration TOML file
[teleport]
auth_server = "cs-training-node-1:3025" 
client_key = "/var/lib/teleport/auth.key"
client_crt = "/var/lib/teleport/auth.crt"
root_cas = "/var/lib/teleport/auth.cas"

[slack]
token = "xoxb-<redacted>"
secret = "<redacted>"
channel = "teleport-training-test-1"

[http]
public_addr = "cs-training-node-1.<redacted>.io"
listen_addr = ":8081"
https_key_file = "/etc/letsencrypt/live/cs-training-node-1.<redacted>.io/privkey.pem"
https_cert_file = "/etc/letsencrypt/live/cs-training-node-1.<redacted>.io/fullchain.pem"

[log]
output = "/var/lib/teleport/slack.log"
severity = "DEBUG"
```

**Comment by xnutsive** [comment]
@travelton, thanks for the detailed report! 

The scopes themselves look fine in your screenshots. First thing to check is if the bot you created is in the channel (#teleport-training-test-1 per the config you posted). The documentation has a paragraph on that, but maybe we should put more emphasis on this. 

Try inviting the bot to the channel, restarting the bot, and retrying. If that still doesn't work — I'll try reproducing this and help you out ;)

**Comment by travelton** [comment]
@xnutsive Correct, the bot is in the channel. I also used curl to send a message by hand using the web hook endpoint Slack provides. 
![image](https://user-images.githubusercontent.com/241714/91741137-e3953c80-eb79-11ea-8954-a353eb7eda4d.png)

**Comment by travelton** [comment]
@xnutsive We discovered that we need `chat:write` scope to resolve this issue. After adding this scope, the bot started working. We need to update docs to include this missing scope.

**Comment by nategadzhi** [comment]
I'll pick that up. This applies to teleport-slack 0.2.0, so should be updated in the docs for the current version, too.

**Comment by marshall-lee** [comment]
Required slack scopes are `chat:write`, `users:read` and `users:read.email`.

https://github.com/gravitational/teleport-plugins/blob/master/access/slack/INSTALL.md#selecting-oauth-scopes
