### ISSUE TITLE
We need to vendor go-toml

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#15]
When trying to build the plugin on a fresh bot I ran into an issue, @fspmarshall has said it's a bug and we should vendor http://github.com/pelletier/go-toml

**Comment by xnutsive** [comment]
Yep, I've had to to `go dep` and install it manually as a workaround.

**Comment by xnutsive** [comment]
Since plugins repo vendor is based on the teleport repo vendoring, should we fix vendor it in the teleport repo?

**Comment by fspmarshall** [comment]
@xnutsive The `go-toml` dependency is specific to this project, and should be vendored here.  The hacky vendoring is a temporary fix because `teleport` hasn't been updated to use `modules` yet.

**Comment by DarthSim** [comment]
Since we try to keep the stack similar to Teleport, I think it makes sense to switch to Yaml.
