### ISSUE TITLE
Tracking: grafana JWT support

### ISSUE THREAD

**Issue by natikgadzhi** [gravitational/teleport-plugins#155]
This is a tracking issue to have a checkbox in the milestone for Teleport Apps support. 
@marshall-lee already filed the PR with Grafana here: https://github.com/grafana/grafana/pull/29995

**Comment by nategadzhi** [comment]
@marshall-lee have implemented the feature, and added the documentation, too. Last bump 4 days ago — probably makes sense to nudge them again.
