### ISSUE TITLE
Tracking: Dockerize Teleport Plugins and add them to our Helm Charts

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport-plugins#160]
Publish docker images of the teleport plugins. Ideally, it would be great if they were included in the Teleport helm chart as optional via the values.yaml. The instructions for the plugins being for bare metal adds a bit of a barrier for a quickstart for containerized organization.

--- 
Walt's edit:

This is a goal for 2022-04.  We're tracking the following subtasks:

- [x] https://github.com/gravitational/teleport-plugins/issues/438
- [x] https://github.com/gravitational/teleport-plugins/issues/439

**Comment by nategadzhi** [comment]
We already have dockerized plugins with a demo scenario and an excruciatingly long readme in [/docker]. Arguably, since Teleport's images are now publicly available on Quay, it would make sense to clean those images up a bit, but then we can easily dockerize them and publish them as a part of our release process. 

What's the urgency on this? OK if we work on this in March?

**Comment by jon-can** [comment]
This is a nice-to-have so March is no problem. Thank you.

**Comment by jon-can** [comment]
I have someone else asking for this. Any updates on this? Thanks.

**Comment by wadells** [comment]
@marshall-lee: I'm going to be working on this with my team -- let me know if you have any advice or partial work on it you'd like to hand off.

**Comment by russjones** [comment]
@jimbishopp @kbence Are the docs merged for this? Can we close this out?

**Comment by russjones** [comment]
@kbence I see that the docs PRs are still open, can you apply changes requested and then merge these PRs?

This task is not complete until documentation is available and customers can benefit from the Teleport Plugins Helm Charts.

* https://github.com/gravitational/teleport/pull/13732
* https://github.com/gravitational/teleport/pull/13730
* https://github.com/gravitational/teleport/pull/13729
* https://github.com/gravitational/teleport/pull/13728
* https://github.com/gravitational/teleport/pull/13726

**Comment by russjones** [comment]
@jimbishopp @kbence I think all the documentation is now merged, can we close this ticket?
