### ISSUE TITLE
Terraform Provider: Generate valid resource maps

### ISSUE THREAD

**Issue by nategadzhi** [gravitational/teleport-plugins#164]
Terraform Provider needs resources to be defined as `schema.Resource` that does two things: 
1. Describes the HCL format that the resource accepts as a description of a resource
2. Provides functions that unmarshall data from the HCL-specific data provider format into the API-friendly data, and provide CRUD functionality. 
3. Optionally, provide functionality to import existing objects from the API to the Terraform state, etc. 

This issue focus on the first aspect of it — providing a valid and accurate Terraform Resource Schemas. Those schemas are extremely verbose, and in theory can be generated from the types prototype that Teleport already has in types.proto. Therefore, we're using a small protoc plugin utility to generate those schemas with protoc: [protoc-gen-tfschema](https://github.com/nategadzhi/protoc-gen-tfschema). 

It already generates schemas, but I have concerns whether those are accurate. We'll need a few more hours of work once we start actively testing the provider.

**Comment by gzigzigzeo** [comment]
This is done, we may mark it as resolved. Here's the latest state of the generator: https://github.com/gzigzigzeo/protoc-gen-terraform

**Comment by klizhentas** [comment]
@gzigzigzeo can you please send all the code including protoc gen code generator as PR to the plugins with Apache 2 license?

**Comment by gzigzigzeo** [comment]
@klizhentas Sure, will do. I guess, after I do so, my repo must be removed, right? Don't you think that keeping code generator in separate repo under /gravitational namespace would be a good idea in case someone decides to provide some PRs related to code generator only?

**Comment by klizhentas** [comment]
@gzigzigzeo sure, separate repo in gravitational is OK too, let me create one and give you access
