### ISSUE TITLE
Terraform Provider: Unmarshall data from schema.ResourceData

### ISSUE THREAD

**Issue by nategadzhi** [gravitational/teleport-plugins#165]
`schema.Resource` in #164 will need to unmarshall data and then send it to the API. This issue covers the unmarshalling part. 

Terraform provides the HCL values parsed into a `schema.ResourceData` that is a `map[string]interface{}`. We need to write a set of helpers and generate functions that use those helpers to unmarshall data from that into Teleport structs, i.e. into`UserV2`.

Two requirements: 
- Safe key lookups. If a certain key isn't there — add a Diag and return an error. 
- Safe type casting. If a certain key contains data that can't be casted into the required type — add a Diag and return an error.

**Comment by gzigzigzeo** [comment]
This task is done. However, some bugs might still raise during the upcoming implementation.
