### ISSUE TITLE
Add Access Workflow Notes to Slack notifications

### ISSUE THREAD

**Issue by nategadzhi** [gravitational/teleport-plugins#184]
Improve the notifications content. This does not depend on #183 and can be shipped independently.

- [ ] Add the request note to the body of the Slack notification

Access Workflows added a way for a user to provide a note about why they need the roles they requested. We need to show that note in the notifications. 

- [ ] Add response note to the body of the Slack notification

If the request was processed outside of Slack and Slack received a notification about that, the notification message should contain the response reason note, and a list of accepted / denied roles.

- [ ] Update documentation

**Comment by berdee** [comment]
done in #258
