### ISSUE TITLE
Split out Enterprise/OSS Mattermost integration

### ISSUE THREAD

**Issue by nategadzhi** [gravitational/teleport-plugins#187]
Similar to #183, implement Mattermost enterprise (readonly, DMs) and OSS (shared channel notification + notification-only mode) integrations. 

### Mattermost Enterprise

- [ ] Implement Mattermost users mapping to Teleport users mapping
- [ ] Send Mattermost DMs to corresponding users for new access requests, those DMs should contain links to Teleport Web UI
- [ ] Send Access Request notification when a request is approved or denied to a shared channel on Mattermost

### Mattermost OSS
- [ ] Support notification-only (readonly) mode for Mattermost integration
- [ ] Support access request notes in the notification body (like in #184)

### Documentation

- [ ] Review and update the documentation on the website
- [ ] Review and update docs in install.md

**Comment by klizhentas** [comment]
We should try to deliver by April 7th 

https://github.com/gravitational/teleport/issues/5683
