### ISSUE TITLE
Discussion: Jira and Gitlab workflows

### ISSUE THREAD

**Issue by nategadzhi** [gravitational/teleport-plugins#190]
Slack, Mattermost, and Pagerduty will have Enterprise versions that only notify the platform of access requests and link back to Teleport for the user to take action. 

Jira and Gitlab workflows however are currently built around users dragging and dropping access-request-issues into Approved or Denied columns. I don't know of an obvious and intuitive way to change that workflow to support readonly Enterprise mode, especially with multi-approvals support. 

One way to do this is to have Enterprise integrations that won't support dragdrop at all, and would just file a new Gitlab / Jira issue into a configured column (status), defaulting to “inbox” or the leftmost column on a board. We could achieve this behavior by: 
1. Adding a config key for the default new access request column, and 
2. Adding a config key to enable the readonly mode (i.e. don't create approved/denied columns and don't do anything on dragdrop) that would work with or without Enterprise. 

## General behavior for all plugins

Another point I just thought about is that all our integrations, when running against Teleport Enterprise, if they only have `access_request: ['read']` permission, but the user configured the integration to support dragdrop or explicit approvals via the integration, should: 
1. Send a warning to STDOUT early (health check at startup?)
2. Send a warning to log when the action was taken (i.e. a user clicked approval Slack button, but the plugin doesn't have the permission to write access request). I'm pretty sure it'll log an error now.
3. Use the 3rd party system UI (Slack message, Jira issue comment, etc) to warn the user that no action was taken because the plugin doesn't have the permission (and it's a good security practice to not trust it, for Enterprise version).

Currently, `teleport-slack`, when runs in notification-only mode, will NOT show approval buttons, will log an error if it receives a webhook, but will not show any indication of that error to the users on Slack itself.

WDYT @klizhentas?

**Comment by berdee** [comment]
Closed as stale.
