### ISSUE TITLE
Implement a lambda function that rotates tokens and publishes to AWS SSM

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport-plugins#198]
## Cloud

Cloud users are wondering how to join nodes in a reproducible way. It's easy using new golang api. Issue a longer lived token creator credentials and give them to a lambda function. This function will publish and rotate short lived join tokens for nodes, apps, etc.

**Comment by aelkugia** [comment]
@klizhentas do we have a timeline on this? This is a customer blocker for exploring Teleport Cloud

**Comment by klizhentas** [comment]
We are going to implement it using AWS signature algorithm
