### ISSUE TITLE
Can't download v6.1.0 plugin

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#208]
While testing the Slack plugin, I'm unable to download the file since it's throwing a 404.

```
$ curl -L https://get.gravitational.com/teleport-mattermost-v6.1.0-linux-amd64-bin.tar.gz
404 page not found
```

I downloaded https://github.com/gravitational/teleport-plugins/releases/tag/v6.1.0 but it's the source code vs the compiled package.

**Comment by benarent** [comment]
FYI @klizhentas @webvictim

**Comment by webvictim** [comment]
https://github.com/gravitational/teleport-plugins/releases/tag/v6.1.0 says `To use the plugins, please build from repository.` - not sure we've published any artifacts yet.

**Comment by webvictim** [comment]
At any rate, the tagging format expected by Drone to publish artifacts is `teleport-<plugin>-v<version>` currently. The Drone config/publishing process may need overhauling somewhat if we're changing the versioning scheme.

**Comment by benarent** [comment]
> says `To use the plugins, please build from repository.` - not sure we've published any artifacts yet.

We've instructions here, https://goteleport.com/docs/access-controls/guides/dual-authz/#setup-teleport-bot I can switch the order to focus on building from source first.

**Comment by webvictim** [comment]
@klizhentas Is the idea that we should still be publishing artifacts for the plugins? I can overhaul Drone to publish the new versions if so.

**Comment by benarent** [comment]
This has been fixed. PR for content is here https://github.com/gravitational/teleport/pull/6434
