### ISSUE TITLE
watcher initialization timed out. Reconnecting... errors

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#21]
While testing, I didn't manage to get the bot running. I ended out with these errors. We should ideally provide a more actionable and friendlier message. 

```
teleport-421-proxy ~/teleport-access-slackbot: sudo ./slackbot start slackbot.toml
INFO[0000] Starting Teleport Access Slackbot 0.1.0-dev.1:
INFO[0000] Starting server on :8081
INFO[0000] Starting a request watcher...
ERRO[0005] Watcher connection error: watcher initialization timed out. Reconnecting...
ERRO[0010] Watcher connection error: watcher initialization timed out. Reconnecting...
ERRO[0015] Watcher connection error: watcher initialization timed out. Reconnecting...
ERRO[0020] Watcher connection error: watcher initialization timed out. Reconnecting...
ERRO[0025] Watcher connection error: watcher initialization timed out. Reconnecting...
ERRO[0030] Watcher connection error: watcher initialization timed out. Reconnecting...
```

**Comment by benarent** [comment]
This should be fixed by https://github.com/gravitational/teleport-plugins/issues/12 .

**Comment by marshall-lee** [comment]
@benarent No, it's unlikely related to #12 which is about http listener but your error comes from Teleport.

The error should be renamed to something like "Couldn't connect to Teleport auth server" but it cannot say more, i.e. the reason why it couldn't connect.
Possible reasons: can't see a server, certificate is invalid/expired.

Another  if you set `auth-server` config entry to something like "localhost:3025"`, then `auth_service.public_addr` in Teleport config must also be `localhost`.
