### ISSUE TITLE
Document application and database resources in Terraform

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport-plugins#218]
Add support for apps and databases in Terraform.

**Comment by r0mant** [comment]
@gzigzigzeo FYI we now have Application and Database resources in Teleport so this can now be implemented:

- [AppV3 proto spec](https://github.com/gravitational/teleport/blob/bddc54d8c489caaf42c51c647ce4f739a42c9ceb/api/types/types.proto#L375-L389)
- [App resource](https://github.com/gravitational/teleport/blob/bddc54d8c489caaf42c51c647ce4f739a42c9ceb/api/types/app.go)
- [App resource APIs](https://github.com/gravitational/teleport/blob/bddc54d8c489caaf42c51c647ce4f739a42c9ceb/api/client/client.go#L1881-L1936)
- [DatabaseV3 proto spec](
https://github.com/gravitational/teleport/blob/bddc54d8c489caaf42c51c647ce4f739a42c9ceb/api/types/types.proto#L221-L235)
- [Database resource](https://github.com/gravitational/teleport/blob/bddc54d8c489caaf42c51c647ce4f739a42c9ceb/api/types/database.go)
- [Database resource APIs](https://github.com/gravitational/teleport/blob/bddc54d8c489caaf42c51c647ce4f739a42c9ceb/api/client/client.go#L1938-L1993)

**Comment by r0mant** [comment]
@gzigzigzeo Was this ever implemented? @marcoandredinis joined the integrations team and I was thinking we could use this as one of warmup items to get to know the terraform provider better.

**Comment by gzigzigzeo** [comment]
@r0mant Yes, App and Database were implemented several releases ago. We are waiting on the reference docs to be merged.

**Comment by alexfornuto** [comment]
Pre-assigning to @ptgott to look into auto-generation possibilities. If not possible or feasible, un-assign for next available writer.

**Comment by ptgott** [comment]
The `gravitational/protoc-gen-terraform` repo before [this PR](https://github.com/gravitational/protoc-gen-terraform/pull/15) had a [`writeRef` function](https://github.com/gravitational/protoc-gen-terraform/blob/6a42a69cfb1bb7561ba53e326df45f2f0dce5c20/plugin/main.go#L162-L176) that wrote `Message`s to a [reference template](https://github.com/gravitational/protoc-gen-terraform/blob/6a42a69cfb1bb7561ba53e326df45f2f0dce5c20/render/_tpl/ref.tpl), so we could consider restoring something similar to this logic and switching it on using a config/CLI flag. I think the `Message` type changed a bit since then, though.

**Comment by marcoandredinis** [comment]
Did you consider this tool?
https://github.com/hashicorp/terraform-plugin-docs
I think I've already shared this tool in a similar issue. If you were already aware of it, sorry for the noise.

**Comment by ptgott** [comment]
That looks promising—building the reference via the `protoc-gen-terraform` plugin would mean that it is always up to date, and would save us the step of building the provider source, but `terraform-plugin-docs` is less work for us. I'll try the `terraform-plugin-docs` approach first, and if it adds too much overhead, we can think about adjusting `protoc-gen-terraform`.

**Comment by ptgott** [comment]
Update: Engineering will take this on and update the reference manually. We will explore auto-generation later on.
