### ISSUE TITLE
PagerDuty incident auto behavior

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport-plugins#219]
## Description

Support two modes, notification and schedule

**Notification mode**

In notification mode, the system will create an incident whenever someone will request access as a privileged user.
The incident will contain a link to the teleport's access request. The plugin will not have any permissions except read permission on access requests.

**Auto-approve mode**

In this mode, pager duty plugin will approve a users' access request if there is an active incident assigned to a user and user has requested an access.

Implementation:

* A user requests access to a privileged role
* Pagerduty plugin approves an access request if:
  * There is an active incident in the target list of support schedules
  * A user is assigned to the incident matches the username in the access request
  * Pager duty will attempt to approve the access request and grant the roles.

**Additional notes**

* [ ] Update the plugin to use the new API
* [ ] Target release May 5th (6.2)

**Comment by klizhentas** [comment]
@marshall-lee let's target 6.2 release (May 5th)

**Comment by klizhentas** [comment]
@marshall-lee docs on system annotations:

https://github.com/gravitational/teleport/issues/6557

Here is how I think it should work:

* Devs set team memberships in OIDC, for example `teams.devops`
* Roles should contain the `allow.request.annotations` propagating `teams.devops` to the target access requests into `teams` section
* PagerDuty should be allowed to approve requests with limiter `teams` (see where example). So PD will only be allowed to approve a subset of requests, not all access requests
* PD should watch the access requests and auto approve if the team name matches the pagerduty service name and a user email matches the access request and a user is assigned to this service
 * [ ] As an option, require active incident assigned to a user as well.

This way there will be 0 configuration in pager duty plugin and all mapping will be done by Teleport and PagerDuty.

**Comment by berdee** [comment]
Done in #266
