### ISSUE TITLE
TF_LOG=DEBUG intergration

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport-plugins#223]
Would help us to debug a lot if our plugin logged teleport's log traces when `TF_LOG=DEBUG` was set in the terrafrom apply, otherwise debugging plugins glitches is very hard.

**Comment by gzigzigzeo** [comment]
`api` package is isolated. It does not reference any main Teleport packages, like `tctl`, for instance. So, the problem is that there is no logging in the API, nothing to redirect. I have added some logging into provider, but looks like we need to add some to the `api` package itself too.

**Comment by klizhentas** [comment]
@gzigzigzeo There is no need to add logging to the api package:

* Capture the error from the client and in debug mode use trace.DebugReport wtih TF_LOG
* Capture the logs from google's grpc logger built-into transport and configure it's logging when TF_LOG is set

**Comment by gzigzigzeo** [comment]
@klizhentas Will do for grpc. Client does not produce any kind of logs. Regarding errors: you mean that I should use trace.DebugReport when TF_LOG=DEBUG instead of returning just error message, as I do now?

**Comment by klizhentas** [comment]
@gzigzigzeo yes, `trace.DebugReport` will print stack trace and you will log in the plugin then. That's way with TF_LOG>=DEBUG you will get more info about the error.

**Comment by gzigzigzeo** [comment]
Done
