### ISSUE TITLE
Run terraform tests in drone on PRs

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport-plugins#224]

**Comment by gzigzigzeo** [comment]
Standard time parse constant: RFC3339  = “2006-01-02T15:04:05Z07:00”, but go still parses .ms/.ns (it should not). Appears on cloud only (not sure why yet). Going to introduce custom time comparison fn which will omit ns and solve the problem,

**Comment by wadells** [comment]
We no longer use Drone for CI.  However, we do run some terraform checks in GitHub Actions:

https://github.com/gravitational/teleport/blob/master/.github/workflows/terraform-lint.yaml
