### ISSUE TITLE
Slack Access binaries

### ISSUE THREAD

**Issue by inertial-frame** [gravitational/teleport-plugins#229]
I'm walking through the documentation and have been encountering the following issues when trying to curl and/or download the Slack Access binaries:

![Screen Shot 2021-05-04 at 5 20 54 PM](https://user-images.githubusercontent.com/82530006/117077244-5c4a2b00-acfd-11eb-8ab8-2989161486a6.png)

![Screen Shot 2021-05-04 at 5 21 27 PM](https://user-images.githubusercontent.com/82530006/117077248-5e13ee80-acfd-11eb-87e0-902848e3f9a7.png)

I'm following the current step here: https://goteleport.com/docs/enterprise/workflow/ssh-approval-slack/#installing-the-teleport-slack-plugin - what am I missing here? Is there a specific version we should be recommending?

I'm able to complete the steps via the `make` option.

Thanks!

**Comment by inertial-frame** [comment]
Forgot to add the [raw documentation](https://github.com/gravitational/teleport/tree/branch/v6.1/docs/pages/enterprise/workflow):

  ```bash
  $ curl -L https://get.gravitational.com/teleport-access-slack-v(=teleport.version=)-linux-amd64-bin.tar.gz
  $ tar -xzf teleport-access-slack-v(=teleport.version=)-linux-amd64-bin.tar.gz
  $ cd teleport-access-slack
  $ ./install
  ```

In other words, we are passing in the teleport version.

**Comment by inertial-frame** [comment]
Note - I've temporarily removed this install path in the upcoming 6.2 docs.

**Comment by inertial-frame** [comment]
I am no longer getting the error above using `curl` - also @stevenGravy pointed out that the other articles use `wget` - and `wget` works correctly!

```
wget https://get.gravitational.com/teleport-access-slack-v6.1.0-linux-amd64-bin.tar.gz
```

**Comment by webvictim** [comment]
You can also `curl -LO...` so you don't have to provide an output filename.
