### ISSUE TITLE
Slack Plugin not connecting through Web port, Teleport cloud

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport-plugins#239]
I configured a Slack plugin and attempted to connect through the enterprise.teleport.sh:443 connection.  The x509 certificate is thrown.

```
[teleport]
auth_server = "enterprise.teleport.sh:443" # Teleport Auth Server GRPC API address
client_key = "/var/lib/teleport/plugins/auth.key" # Teleport GRPC client secret key
client_crt = "/var/lib/teleport/plugins/auth.crt" # Teleport GRPC client certificate
root_cas = "/var/lib/teleport/plugins/auth.cas"  # Teleport cluster CA certs

```
Log:
```bash
$ sudo ./teleport-slack start -c ./configure.toml 
INFO   Starting Teleport Access Slack Plugin 6.1.1: slack/app.go:72
ERRO   Unable to get Teleport server version slack/app.go:151
ERRO   Terminating... error:[
ERROR REPORT:
Original Error: *status.Error rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = &#34;transport: authentication handshake failed: x509: certificate is valid for *.enterprise.teleport.sh, enterprise.teleport.sh, not teleport.cluster.local&#34;
Stack Trace:
        /home/ubuntu/teleport-plugins/vendor/github.com/gravitational/teleport/api/client/client.go:412 github.com/gravitational/teleport/api/client.(*Client).Ping
        /home/ubuntu/teleport-plugins/access/slack/app.go:146 main.(*App).checkTeleportVersion
        /home/ubuntu/teleport-plugins/access/slack/app.go:121 main.(*App).init
        /home/ubuntu/teleport-plugins/access/slack/app.go:91 main.(*App).run
        /home/ubuntu/teleport-plugins/lib/process.go:216 github.com/gravitational/teleport-plugins/lib.NewServiceJob.func1
        /home/ubuntu/teleport-plugins/lib/process.go:237 github.com/gravitational/teleport-plugins/lib.(*serviceJob).DoJob
        /home/ubuntu/teleport-plugins/lib/process.go:83 github.com/gravitational/teleport-plugins/lib.NewProcess.func2.1
        /snap/go/7360/src/runtime/asm_amd64.s:1371 runtime.goexit
User Message: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = &#34;transport: authentication handshake failed: x509: certificate is valid for *.enterprise.teleport.sh, enterprise.teleport.sh, not teleport.cluster.local&#34;] lib/bail.go:17
```

**Comment by stevenGravy** [comment]
As with the Terraform provider (https://github.com/gravitational/teleport-plugins/pull/231#pullrequestreview-664958700)  using the identity file is required going through the proxy web port. The plugin will require a method of specifying a identity file besides the certificate files.

**Comment by marshall-lee** [comment]
Connection to web port using TLS certificate won't work. To get it work, #213 needs to be merged.

**Comment by inertial-frame** [comment]
I've tried this with both `443` and `3025` for non-cloud and get that same issue. Tried with:

1. `tctl auth sign --format=tls --user=access-plugin --out=auth --ttl=720h`
2. `tctl auth sign --user=access-plugin --format=file --out=access-plugin.pem`

Relevant for: https://github.com/gravitational/teleport/pull/7041 and https://github.com/gravitational/teleport/pull/7074

**Comment by marshall-lee** [comment]
```
authentication handshake failed: x509: certificate is valid for *.enterprise.teleport.sh, enterprise.teleport.sh,
 not teleport.cluster.local
```

It does matter what server name you provide when you generate certificates and what server name you provide to a plugin via configuration file.

The `auth_server` setting of plugin MUST match the `--auth-server` option you used when generating a certificate, i.e.

Config:

```
[teleport]
auth_server = "your.server.example.com:PORT"
```

Generating a certificate:

```
tctl --auth-server=your.server.example.com:PORT sign --user=... --format=...
```

The server name is embedded into a certificate file so it really matters that names are matching.

THE CAVEAT:

if you generated a certificate using `tctl` command WITHOUT providing an `--auth-server` option then such certificate can ONLY be used when connecting the plugin locally using `localhost:PORT` server name. 

So, you cannot generate a certificate locally with `--auth-server` option and then use this certificate when connecting via remote hostname which is resolved by DNS. Generate cert locally -> use it locally. Generate it remotely -> use remotely.

Hope it helps.

**Comment by inertial-frame** [comment]
The following command was able to connect:

```
sudo tctl auth --auth-server=slacktest.go-teleport.com:3025 sign --format=tls --user=access-plugin --out=auth --ttl=1h
```

The message has indeed changed to: `INFO   Starting Teleport Access Slack Plugin 6.2.0: slack/app.go:72` alone without the other subsequent logging messages.

**Comment by marshall-lee** [comment]
> The message has indeed changed to: INFO Starting Teleport Access Slack Plugin 6.2.0: slack/app.go:72 alone without the other subsequent logging messages.

Logging must be improved. Printing only "Starting Teleport Access Slack Plugin" misguides the user, there should also be something like "Slack Plugin is ready".

**Comment by berdee** [comment]
Logging was improved in https://github.com/gravitational/teleport-plugins/pull/258
