### ISSUE TITLE
Recommend Port 8081 ? 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#24]
We have designed Teleport to expose the Proxy, https://gravitational.com/teleport/docs/admin-guide/#ports `error: listen tcp 10.2.1.55:8080: bind: address already in use`

When trying to run the Slackbot on the same  machines as the Proxy, it's not possible due to a port conflict. Should we change the recommended default port? Or keep it the same? @fspmarshall

**Comment by marshall-lee** [comment]
I think for plugins we need something 5-digit, say 30000

**Comment by xnutsive** [comment]
Why 5 digits?

**Comment by xnutsive** [comment]
I can set 8081 for now, and if we make a decision to go for 5 digits later — we can set those up for Slackbot, Jirabot, and others consistently.
