### ISSUE TITLE
Don't output log info to stdout / stderr by default, but add a debug flag to the CLI

### ISSUE THREAD

**Issue by xnutsive** [gravitational/teleport-plugins#25]
Teleport has quite a few useful flags in the binary, and for consistency we'll add a few of them: 

```
vm0:~ teleport help start
usage: teleport start [<flags>]

Starts the Teleport service.

Flags:
  -d, --debug            Enable verbose logging to stderr
      --insecure-no-tls  Disable TLS for the web socket
  -r, --roles            Comma-separated list of roles to start with [proxy,node,auth]
      --pid-file         Full path to the PID file. By default no PID file will be created
      --advertise-ip     IP to advertise to clients if running behind NAT
  -l, --listen-ip        IP address to bind to [0.0.0.0]
      --auth-server      Address of the auth server [127.0.0.1:3025]
      --token            Invitation token to register with an auth server [none]
      --ca-pin           CA pin to validate the Auth Server
      --nodename         Name of this node, defaults to hostname
  -c, --config           Path to a configuration file [/etc/teleport.yaml]
      --bootstrap        Path to bootstrap file (ignored if already initialized)
      --labels           List of labels for this node
      --insecure         Insecure mode disables certificate validation
      --fips             Start Teleport in FedRAMP/FIPS 140-2 mode.
```

For this issue, we want to add `-d, --debug` flag. By default, Slackbot should not output log info (approved / declined / pending requests, and startup events) to the console.  If the startup is successful, it should output that the grpc watcher and the slack listener are up (and on which address:port is the slack listener running). 

If the `-d` option is passed, than it should ouput initialization steps, warnings, and events. Including users identity from #1.

**Comment by marshall-lee** [comment]
> For this issue, we want to add -d, --debug flag. By default, Slackbot should not output log info (approved / declined / pending requests, and startup events) to the console

Why it shouldn't? It just only doesn't need to spam log entries with DEBUG severity by default but other entries should be printed. Also, I had already added the `-d` command line flag for raising a logger severity to debug level https://github.com/gravitational/teleport-plugins/pull/4

What we really lack, is a logging configuration of different outputs (`stderr`, `stdout`) and severity. Look https://gravitational.com/teleport/docs/admin-guide/
