### ISSUE TITLE
Create a reference doc with all supported resources

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport-plugins#253]
Please create a reference doc with all supported resources for terraform, 
use the structure and configuration from here:

https://goteleport.com/docs/kubernetes-access/helm/reference/
https://github.com/gravitational/teleport/blob/master/docs/pages/kubernetes-access/helm/reference.mdx
https://github.com/gravitational/teleport/blob/master/docs/config.json#L47

Send a PR to teleport docs, setup section under guides.

**Comment by gzigzigzeo** [comment]
As far as I know, this one is done, but it might require an update once we merge my latest PRs
