### ISSUE TITLE
Provide a better error message. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#26]
![image](https://user-images.githubusercontent.com/559288/72840546-52580200-3c49-11ea-8cb6-29cfbcb27792.png)

I would recommend something more user friendly. 

Teleport Slackbot Verification failed. Please double check your Slackbot configuration.

**Comment by marshall-lee** [comment]
Need to forbit `GET` requests to this endpoint. Seeing "verification failed" error in browser could be confusing since this endpoint is not for browsers.

**Comment by benarent** [comment]
Could we add a `/webapi/ping` instead, that'll output the status of the plugin? We do this for Teleport and it's a helpful debugging tool. https://teleport-4-2-1.practice.io:3080/webapi/ping

**Comment by marshall-lee** [comment]
@benarent could you please create a separate issue about `/webapi/bing`?
