### ISSUE TITLE
Create auth preference resource

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport-plugins#261]
The PR has been merged in master and will be backported to 6.2 this week:

https://github.com/gravitational/teleport/pull/7220

Release the resource, update the docs. For now test locally

**Comment by Joerger** [comment]
@gzigzigzeo Here is the backport PR for 6.2 https://github.com/gravitational/teleport/pull/7380.

**Comment by gzigzigzeo** [comment]
This one is ready and approved. Can be merged: https://github.com/gravitational/teleport-plugins/pull/263
