### ISSUE TITLE
Include Cluster name in Request

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#27]
Currently:
```
Request e1be5fa8-b816-4fd4-a6ce-833fa2497db7
User    bob
Role(s) admin
Status  PENDING
```

With Cluster Name:
```
Request 1e0bd688-6f2a-4312-98fb-83244de0db0a
Cluster teleport-421-auth
User    bob
Role(s) admin
Status  DENIED
```

**Comment by marshall-lee** [comment]
Ping @fspmarshall not sure can we achieve this or not

**Comment by marshall-lee** [comment]
@benarent @fspmarshall 

Is it really necessary? It will be a constant every time. I think if someone wants to run slackbot across different clusters, it's worth to create separate Slack channels for these clusters.
