### ISSUE TITLE
Set attribute after token created

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport-plugins#274]
From a user:

```
token = {
  "id" = "truss-nonprod-cmh"
  "kind" = "token"
  "metadata" = [
    {
      "description" = ""
      "expires" = "2022-10-12T07:20:51.2Z"
      "labels" = {}
      "name" = "truss-nonprod-cmh"
      "namespace" = "default"
    },
  ]
  "spec" = [
    {
      "roles" = [
        "Kube",
      ]
    },
  ]
  "version" = "v2"
}
```

I would expect the resourceProvisionTokenCreate function to capture the API response and set it as an attribute on the resource.

…akin to [this](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_iam_user_login_profile.go#L162), from the aws_iam_user_login_profile resource.

**Comment by adamgoose** [comment]
👋 I'm the "user." Great work so far on the Terraform Provider; can't wait to iron out some of this nuance!

**Comment by gzigzigzeo** [comment]
@adamgoose Hey. Am I correct that you'd like to have AWS response dump captured somewhere in the Terraform state?
