### ISSUE TITLE
Improve Slackbot Message

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#28]
We currently use a very minimal Slackbot message.

## Before
<img width="638" alt="Image 2020-01-21 at 2 49 14 PM" src="https://user-images.githubusercontent.com/559288/72851262-f64ca800-3c5f-11ea-89e4-5cdc305a7e20.png">

## Proposal 
I've extended one of Slacks official message templates. 
https://gist.github.com/benarent/e5368c8a1f867dc778dfa0095dd94137
![image](https://user-images.githubusercontent.com/559288/72851232-e765f580-3c5f-11ea-8da4-a02f34321754.png)

**Comment by xnutsive** [comment]
Once @marshall-lee've merged the big refactoring PR by @DarthSim, I can work on that. Should be done by end of week.
