### ISSUE TITLE
How do I add `aws_role_arns` using Terraform? 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#285]
I'm currently trying to add role using AWS Console. I've tried a few variants for `aws_role_arns`, but can't find the correct options. Is it supported / need to be added? 

```
resource "teleport_role" "aws_console" {
  metadata {
    name        = "aws-console-access"
  }

  spec {
  options {
      max_session_ttl = "10h"
    }
  
    allow {
     aws_role_arns = ["arn:aws:iam::1234567890:role/ec2-read-only"]

      app_labels {
        key = "*"
        value = ["*"]
      } 
      
     # aws_role_arns = ["arn:aws:iam::${aws_account_id}:role/aws-console-access"]
   
    }

    deny {
    }
  }
}
```

**Comment by benarent** [comment]
@Joerger @r0mant , let me know if you have pointers for me.

**Comment by gzigzigzeo** [comment]
@benarent It looks like provider schema is little behind actual API resource schema. I will update it and get back to you.

**Comment by gzigzigzeo** [comment]
@benarent I have fixed this. PR should be merged before the next provider release.

**Comment by gzigzigzeo** [comment]
https://github.com/gravitational/teleport-plugins/pull/288
