### ISSUE TITLE
Terraform Provider recognizing changes when fields were generated

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport-plugins#287]
If fields are left blank in the Terraform config such as in the SAML Auth connector these are identified as modified when they were auto-generated by Teleport.  Here is an example

```
  # teleport_saml_connector.saml will be updated in-place
  ~ resource "teleport_saml_connector" "saml" {
        id      = "okta-saml"
        # (2 unchanged attributes hidden)


      ~ spec {
          - audience                   = "https://teleport.example.com.com/v1/webapi/saml/acs" -> null
          - issuer                     = "http://www.okta.com/<snipped>" -> null
          - service_provider_issuer    = "https://teleport.example.com/v1/webapi/saml/acs" -> null
          - sso                        = "https://canva.oktapreview.com/app/teleport/<snipped>/sso/saml" -> null
            # (3 unchanged attributes hidden)
```

**Comment by gzigzigzeo** [comment]
Could you please provide exact config you are using to create resource along with Teleport version? Unfortunately, this behaviour is common for Terraform. I could mark such fields as Computed or I could provide workaround which drops computed defaults from a state, but I would appreciate if you send me specific config to reproduce this behaviour locally @stevenGravy

**Comment by stevenGravy** [comment]
this was from a version 6.2.7 on-prem @gzigzigzeo .  I'll look at getting a repeatable example.

**Comment by gzigzigzeo** [comment]
@stevenGravy Got it. I'll try to reproduce this locally and get back to you. Just to understand better, why do you need to specify version explicitly in your config?

**Comment by gzigzigzeo** [comment]
@stevenGravy One more question: you are using the latest provider version, right?

**Comment by stevenGravy** [comment]
Yes, I've confirmed it happening in the latest and 6.2.7

**Comment by stevenGravy** [comment]
For the roles issue the V4 provides more limited allow defaults which is preferred.

**Comment by gzigzigzeo** [comment]
@stevenGravy Sure. So, you added version = "v4" to the config to upgrade the role, correct?

**Comment by stevenGravy** [comment]
the initial creation had it.  if you run `terraform plan` it recognizes it as a change.

**Comment by gzigzigzeo** [comment]
Yes, the initial creation had it as version = "v3". I just want to clarify: was it specified explicitly as version="v3" written in the config during initial creation, or was it silently assigned from the default value and appeared in the state?

**Comment by stevenGravy** [comment]
it was initially assigned v4 for the creation.  it does get set as V4 in the role. but still gets the change report in terraform on a `terraform plan`

**Comment by gzigzigzeo** [comment]
Okay, got it, thank you for the clarification. This issue is my primary focus right now, going to get back to you tomorrow.

**Comment by gzigzigzeo** [comment]
https://github.com/gravitational/teleport-plugins/pull/289
