### ISSUE TITLE
New plugin: email

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport-plugins#292]
What:

Email plugin sending notifications when new access request is created.

Support transports:

* [ ] mTLS SMTP
* [ ] Mailgun HTTPS API

Support multiple email aliases and channels

**Comment by Moulick** [comment]
This will be super useful

**Comment by pschisa** [comment]
We do have an email plugin now:
https://github.com/gravitational/teleport-plugins/tree/master/access/email
