### ISSUE TITLE
Error Log should update state

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#30]
Currently when a request is denied, it show's that it's still `State:PENDING` 

```
INFO[0452] Denying request {ID:1e0bd688-6f2a-4312-98fb-83244de0db0a User:bob Roles:[admin] State:PENDING}

INFO[0727] Approving request {ID:7552499c-98ec-4cd7-a2fe-1820ba664a51 User:bob Roles:[admin] State:PENDING}
```

**Comment by xnutsive** [comment]
Yep, this should have a clear language about several things: 

1. Previous state and current state
2. User who requested the permission
3. Slack user who granted the permission (#1)
