### ISSUE TITLE
Build official Docker/OCI compliant images for plug-ins.

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport-plugins#307]
Right now installing and running plugins is a very manual process. Would be neat to have the ability to have our plugins on our official Quay repo and/or Docker hub.

A `docker pull teleport/slack-plugin:latest` would be nifty feature.

**Comment by pschisa** [comment]
+1 for getting a plugins image into our official repo

**Comment by crashdump** [comment]
We're specifically interested in a `teleport-plugins` Docker image containing the `event-handler` binaries.
