### ISSUE TITLE
The Slack plugin can't get channel 

### ISSUE THREAD

**Issue by tpang-ameame** [gravitational/teleport-plugins#322]
Hi,

When followed instruction in page: https://goteleport.com/docs/enterprise/workflow/ssh-approval-slack/, met that the plugin can read a request but can't forward to slack because of missing channel. Here are some info:

Teleport version: 6.2.8 

Plugin output:
```
DEBU   DEBUG logging enabled slack/main.go:81
INFO   Starting Teleport Access Slack Plugin 7.1.0: slack/app.go:76
DEBU   Checking Teleport server version slack/app.go:151
DEBU   Starting Slack API health check... slack/app.go:140
DEBU   Slack API health check finished ok slack/app.go:145
DEBU   Watcher connected watcherjob/watcherjob.go:109
INFO   Plugin is ready slack/app.go:97
WARN   No channel to post request_id:74c8811c-b770-49a8-8839-519aee268c0a request_op:put request_state:PENDING slack/app.go:235
```

In Slack, teleport app created and already invited to channel.

Thanks.

**Comment by TroyPang** [comment]
Could you please share more info about this part?
https://goteleport.com/docs/ver/6.1/enterprise/workflow/ssh-approval-slack/#editing-the-config-file
Seems screenshot here is missing some configurations?

Thanks.

**Comment by marshall-lee** [comment]
@tpang-ameame

Hi!
"No channel to post" message means that you didn't set up where the plugin should post.
There're to ways the plugin picks a channel to post:

1. Set the `recipients` setting in a configuration file. 
Just set it to a channel name or to a email of Slack user:
```toml
[slack]
recipients = ["some-channel", "some-user@example.com"]
```
2. Fill the "Suggested reviewers" list in Web UI when you create a request. This is the list of Teleport user names the plugin treats as a list of emails of users in Slack.

**Comment by Joerger** [comment]
Feel free to reopen this issue if you are still having trouble setting this up.
