### ISSUE TITLE
Terraform Provider - Bug when adding SAML connector

### ISSUE THREAD

**Issue by yjperez** [gravitational/teleport-plugins#330]
Able to successfully create a SAML auth connector using the provider.  However, after a successful "apply" I can then immediately to a "plan" and terraform thinks it needs to modify the spec.signing_key_pair argument, specifically it wasn't to delete the cert and private_key. Another "apply" says it was successful, but another "plan" says it wants to modify the resource. And we're in an infinite loop. 

The provider should not try to do anything with the signing_key_pair argument. Or is the bug that there's not a way to tell terraform to ignore changes to that attribute?

**Comment by pschisa** [comment]
Should be resolved by #341 , which is waiting on review/closure of https://github.com/gravitational/protoc-gen-terraform/pull/12

**Comment by pschisa** [comment]
#341 has been closed by #357 .  Closing this issue
