### ISSUE TITLE
Session and Identity Locking Conditionals

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport-plugins#343]
What
Users have requested the ability to configure user and identity locks with conditionals such as "lock if there are abundant failed login attempts within a period of time" or "lock after n failed login attempts - requires unlocking by an admin". This would ideally trigger an auto-lock once the condition was met and require admin removal of the lock to disable.

Why
Customer request.

**Comment by klizhentas** [comment]
@gzigzigzeo let's do a research / prototyping of this first and then refine the config and plugins capabilities

**Comment by r0mant** [comment]
This will be possible with Access Monitoring Response which we'll resume working on in Q3.
