### ISSUE TITLE
Ability to tie PagerDuty requests to specific on-call schedules for auto-approvals

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport-plugins#360]
### What
Currently our PagerDuty access workflow plugin integrates with PD Services for access requests auto-approvals, which in turn can have a number of schedules attached. In instances where customers have multiple teams with different schedules tied to a single teleport service, if an individual from Team A who is on-call on Schedule A requests approval, an incident is triggered for ALL schedules attached to the service. There is currently no real way to separate or differentiate schedules for large organizations with multiple teams without creating dozens of individual services on PD, which can get quickly out of hand and be cumbersome to manage. It would be good to have the ability to specify an individual schedule in instances of auto-approval requests, or have some other mechanism to handle auto-approval scenarios through PD.

### Why
Customer use case requirement. 

### Workaround
One potential workaround is creating individual base roles on Teleport and individual services on PD, but this quickly gets out of hand for organizations with 20-30+ on-call schedules and overlapping permission role requirements in Teleport.

**Comment by Aharic** [comment]
Additional context (using 2 teams for simplicity - actual number of teams is in the multiple dozens in customer use case):

An organization has 2 teams in different part of the world: qa-1 and qa-2. These 2 teams share a single Teleport role b/c work scope and permissions for both teams are the same. 

This Teleport role is configured as follows for PagerDuty auto-approval:

```
    request:
      annotations:
        pagerduty_notify_service:
        - teleport
        pagerduty_services:
        - teleport
```

PagerDuty allows a service to be associated with only to a single Escalation Policy. In the case of this organization this service (teleport) is tied to 2 separate escalation policies: qa-1 and qa-2. 

When teleport triggers an access-workflow request for a member in qa-1, it goes to PD and gets auto-approved as requested. The problem, however, comes from the fact that qa-2 is also notified of an incident in the interim, even though the alert is eventually auto-approved and resolved by the plugin.

Attempts to remove the `pagerduty_notify_service` from the requesting role result in the following error and no event being generated at all:

```
DEBU   Failed to determine a notification service info: request annotation "pagerduty_notify_service" is missing request_id:e4ee7e4f-33f2-459d-ba3a-559a3ec83424 request_op:put request_state:PENDING pagerduty/app.go:259
DEBU   Failed to submit approval: user has no incidents assigned pd_user_email:testuser@haric.co pd_user_name:test request_id:e4ee7e4f-33f2-459d-ba3a-559a3ec83424 request_op:put request_state:PENDING pagerduty/app.go:51
```

Attempts to separate the `pagerduty_notify_service` and the `pagerduty_service` used for auto approval as recommended in the README NOTE result in an event being generated, but not auto-resolved:

```
`INFO   Successfully created PagerDuty incident pd_incident_id:Q0IYLBA8ZW253J pd_service_name:teleport-notify request_id:b94ad14b-39a3-4be7-a84a-cfb6853eb109 request_op:put request_state:PENDING pagerduty/app.go:357
DEBU   Failed to submit approval: user has no incidents assigned pd_user_email:testuser@haric.co pd_user_name:test request_id:b94ad14b-39a3-4be7-a84a-cfb6853eb109 request_op:put request_state:PENDING pagerduty/app.go:515
```

**Comment by marshall-lee** [comment]
@Aharic 

> Failed to submit approval: user has no incidents assigned

Auto-approval happens only if there's at least one active incident in the one of the services listed in `pagerduty_services` annotation.

So, no active alerts — no auto-approval of access request. It's because we suppose that someone requests an access because of some alert in PD.

Also some caveat was described in the README:

> - That user is currently on-call in a service "service 1" or "service 2" or in both of them.
> - There's at least one active incident assigned to `alice@example.com` in a service where she's currently on-call.
> - `alice@example.com` requests a role `champion`.
> - Then pagerduty plugin **submits an approval** of Alice's request.
>
> *NOTE* that `pagerduty_services` and `pagerduty_notify_service` annotations **should not overlap.** You cannot use the same service to post notifications in and be on-call in that service. If `pagerduty_services` and `pagerduty_notify_service` overlap then there'll always be an active incident assigned to user - the notification itself is an incident. So the plugin will auto-approve an access every time which is not actually desired.

When you set both `pagerduty_notify_service` and `pagerduty_service` annotations and moreover you set them equal, then you get auto-approval happening always because there's always an active incident assigned to a user — the incident created by a plugin.

My bad, that caveat should be better communicated to a user. I think some checks should be added to a plugin code to warn about an overlapping.
