### ISSUE TITLE
Enable HA for Access Request Plugins

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport-plugins#361]
Currently, Teleport does not support HA for access plugins. If a user tries to run separate instances of a plugin, they will receive duplicate "notifications" for each access request.

It would be beneficial to availability and UX if a user could run two separate instances of a plugin, and only receive one notification in their notification application (e.g. Slack, Jira) for each access request.

**Comment by marshall-lee** [comment]
@corkrean 

Hi! Do you use a latest version?

I thought we fixed the HA issue some time ago when we brought compare-and-swap based check before posting a notification.

If the version you use is really the latest then I'll evaluate it myself and try to add some HA integration tests.

**Comment by corkrean** [comment]
@marshall-lee I was using an older version. I will update my version and try again. Thanks.

**Comment by corkrean** [comment]
I attempted with the newer version and it worked. I will get this added to the docs. https://github.com/gravitational/teleport/issues/8970
