### ISSUE TITLE
Terraform Provider: Invalid provider registry host

### ISSUE THREAD

**Issue by robcoward** [gravitational/teleport-plugins#375]
Just like the closed issue #336 I'm now getting the same error when trying to run `terraform init`.

Using the following:
```
terraform {
  required_providers {
    teleport = {
      version = "~> 7.1"
      source  = "gravitational.com/teleport/teleport"
    }

    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.63"
    }
  }
}
```
When trying to run init, I get the following:
```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding gravitational.com/teleport/teleport versions matching "~> 7.1"...
- Finding latest version of hashicorp/local...
- Finding hashicorp/aws versions matching "~> 3.63"...
- Using hashicorp/local v2.1.0 from the shared cache directory
- Using hashicorp/aws v3.65.0 from the shared cache directory
╷
│ Error: Invalid provider registry host
│
│ The host "gravitational.com" given in in provider source address "gravitational.com/teleport/teleport" does not offer a Terraform provider registry.
╵
```
The closed #336 issue didnt offer any solution - anyone else found / fixed this ?

**Comment by klizhentas** [comment]
@gzigzigzeo can you please take a look when you have a chance?

**Comment by gzigzigzeo** [comment]
@klizhentas Implemented private registry: https://github.com/gravitational/next/pull/603

**Comment by somethingnew2-0** [comment]
For posterity, you need to manually install the terraform provider as documented in the setup guide 
https://goteleport.com/docs/setup/guides/terraform-provider/#step-14-install-terraform-provider

**Comment by robcoward** [comment]
> For posterity, you need to manually install the terraform provider as documented in the setup guide https://goteleport.com/docs/setup/guides/terraform-provider/#step-14-install-terraform-provider

That doesn't help when you don't have access to the system running terraform, such as terraform cloud.

**Comment by ctrlok** [comment]
@robcoward you can use [this instruction](https://support.hashicorp.com/hc/en-us/articles/360016992613-Using-custom-and-community-providers-in-Terraform-Cloud-and-Enterprise) as a workaround for now

**Comment by robcoward** [comment]
> @robcoward you can use [this instruction](https://support.hashicorp.com/hc/en-us/articles/360016992613-Using-custom-and-community-providers-in-Terraform-Cloud-and-Enterprise) as a workaround for now

That looks sweet - I'll give it a try later.... now all I need is for the `provider "teleport" { ... }` block to accept the identity file contents as a string, rather than it being a filename that the provider tries to open.....
