### ISSUE TITLE
General Feedback and Requests for Terraform Provider provision_token functionality

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport-plugins#418]
The following is some general issues and feature requests regarding the Terraform Provider provision_token functionality:

- [ ] Add attributes to the resource
- [ ] If using the `name` value as the actual token vlaue, there's no point in marking the output as sensitive
- [ ] Include the random string generation within the resource code and eliminate `name`, or use `name` as a label instead
- [ ] Modify the expires attribute to accept a fixed value, e.g. 1h, or similar, in other words, save the users the chore of calculating the expiry date every time 
- [ ] Update the documentation to reflect the correct RFC used for date representation; currently the documentation mentions RFC8829 which has nothing to do with date, it's about JavaScript Session Establishment Protocol (JSEP); the RFC for date format is RFC3339

**Comment by gzigzigzeo** [comment]
@pschisa Hey. Could you please clarify this requirements for me? I do not understand the reasoning behind point #2 (why marking name as sensitive is not sufficient), and #3 (include random string generation). Am I correct that you want to generate the token id randomly on create?

**Comment by gzigzigzeo** [comment]
Got it. I've added name auto generation in the next version of the provider. From now on, you may omit name, random string would be generated instead.

Unfortunately, I do not see a way to implement fixed values for expires attribute. Any change in any other property of a token would trigger expires time recalculation from a current time.
