### ISSUE TITLE
Add Desktop Access fields to Terraform Provider

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport-plugins#422]
Add `windows_desktop_labels` and `windows_desktop_logins` that were added to `types.Role` to the Terraform Provider.

May also consider adding `record_sessions.desktop` and `desktop_clipboard` which will most likely be added soon.

**Comment by zmb3** [comment]
This was fixed by @Joerger in 250735cafb3df27b3be75e0945d5e51784f36fed
