### ISSUE TITLE
New Error after upgrading to Terraform Provider 8.2.0 from 8.0.7

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport-plugins#427]
After upgrading the Terraform provider from 8.0.7 to 8.2.0, the Terraform code no longer works and gives the following error:

~~~
Error: field spec.0.allow not found in target struct
~~~

Attaching a santized version of the Terraform provider code.  Please let me know if any further information is required

~~~
resource "random_id" "token" {
  byte_length = 16
}

resource "teleport_provision_token" "token" {
  metadata {
    name    = random_id.token.hex
    expires = timeadd(timestamp(), "1h")
    labels = {
      test = "yes"
    }
  }
  spec {
    roles = ["Kube", "App", "Db"]
  }
}

terraform {
  required_version = ">= 1.0.0"

  required_providers {
    teleport = {
      version = "8.2.0"
      source  = "gravitational.com/teleport/teleport"
    }
  }
}

provider "teleport" {
  addr = ""
}

output "teleport_token" {
  value = random_id.token.hex
}
~~~

**Comment by programmerq** [comment]
I also ran into this in my own lab.

I did some experimenting to try to make it work, but I wasn't able to find a solution.

This change in #408 does change `Allow` to `allow` which may be related: https://github.com/gravitational/teleport-plugins/pull/408/files#diff-160c8d9d2e45912ae5ad2964f3846088b7d9ef45fc606eff48937c4ab7dc9dd4

**Comment by Joerger** [comment]
> This change in #408 does change `Allow` to `allow` which may be related: https://github.com/gravitational/teleport-plugins/pull/408/files#diff-160c8d9d2e45912ae5ad2964f3846088b7d9ef45fc606eff48937c4ab7dc9dd4

This is [likely the culprit](https://github.com/gravitational/teleport-plugins/pull/415#discussion_r796641178), thanks for spotting it.  That'd be my mistake, sorry about that, I'll PR a fix.

@gzigzigzeo Can we find a way to make `gen-schema` idempotent to avoid this issue going forward?

**Comment by gzigzigzeo** [comment]
@Joerger Yes, it's already done in the latest version, which I am working on now. I guess, we need to fix `types.proto` as well.

**Comment by benarent** [comment]
+1 I ran into this issue and had to build from master
