### ISSUE TITLE
Add the ability to set an OIDC auth_connector version in the Terraform provider

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport-plugins#428]
Add the ability to set the `version` value in an OIDC connector via the Terraform provider and document this in the example (https://github.com/gravitational/teleport-plugins/blob/master/terraform/example/oidc_connector.tf).

This is important now that version 3 has been released for the connector to allow for improved Google SSO experience: https://goteleport.com/docs/ver/9.0/enterprise/sso/google-workspace/#create-a-oidc-connector

**Comment by Joerger** [comment]
https://github.com/gravitational/teleport-plugins/pull/431 updates the Terraform provider to use `OIDCConnectorV3`.

I don't believe there is currently a way for the Terraform Provider to make the OIDC Connector version configurable, as the `teleport/api` package only provides one or the other. See https://github.com/gravitational/teleport-plugins/pull/263#discussion_r662515098 for a similar issue.

**Comment by pschisa** [comment]
That will resolve this issue yes, if the provider uses v3 .  Not sure if that will raise any new issues with people expecting to continue using v2 going forward (though that use case seems less likely)
