### ISSUE TITLE
Publish OCI images for teleport plugins

### ISSUE THREAD

**Issue by wadells** [gravitational/teleport-plugins#438]
## Summary
This is a sub-issue of making our teleport plugins more user friendly (https://github.com/gravitational/teleport-plugins/issues/160). This ticket tracks the following dev tasks:

- [x] develop OCI images for all teleport plugins
- [x] make sure these images are validated via CI
- [x] automatically publishing images to a staging location during tag build and master push builds
  - [x] we may need to ensure unique build ids for all commits -- to accommodate pushing untagged commits without overwrite
- [x] copy images from the staging location to the customer facing distribution during promotion
- [x] write dev facing documentation about the images/publishing in this repo
- [x] write customer facing documentation about using images in the teleport docs
- [x] backport all the above to the appropriate branches (probably v9, but worth double checking v8 and prior can be excluded)

**Comment by logand22** [comment]
For the CI portion of this. I noticed both **drone** and **cloudbuild** being used in this repository. Should I lean towards one or the other?

**Comment by wadells** [comment]
> For the CI portion of this. I noticed both **drone** and **cloudbuild** being used in this repository. Should I lean towards one or the other?

Use cloudbuild for CI.  I think we still prefer drone for publishing, as the point of this project isn't to refactor the publishing/promotion pipleline.
 
> > Make sure these images are validated via CI
> 
> Can you clarify what you mean by this?

Ideally, we'd build the docker images before merge, such that if there was a syntax error in the dockerfiles, we'd catch it.

My general thought is:

* PR -> build image, do not publish anywhere, throw it away after completion
* Merge to `master` / `branch/*` or push a tag -> build an image and push to an internal private repo
* Promote a build -> copy the bits from the internal private repo to a customer facing repo

My concern here would be: can we safely build an image at the CI stage.  DinD hasn't been sufficient isolation previously, and I'm not sure what options GCB offers for building images at the CI phase.  Build after approval (for external contributors) is fine.

**Comment by tcsc** [comment]
> Use cloudbuild for CI. I think we still prefer Drone for publishing

Yeah. The _eventual_ goal is GCB for everything, but we're a long, long way from there.

> Can we safely build an image at the CI stage
 
GCB can definitely build/push images to a docker repo, so the question becomes can we do it _safely_. Reasonably sure that it's done by mounting the docker socket into the build container (i.e. Docker-out-of-Docker), with whatever implications that has (and I don't know enough about that to comment on off the top of my head).

**Comment by logand22** [comment]
An update: 

Merging via tag and promoting to quay have been merged. See https://github.com/gravitational/teleport-plugins/pull/456 and https://github.com/gravitational/teleport-plugins/pull/466

https://github.com/gravitational/teleport-plugins/issues/460 tracks the issue of building and pushing docker images on push to master. This would allow developers to test their changes without having to create a tag.

I'm independently verified the pipeline but am waiting for https://github.com/gravitational/teleport-plugins/pull/469 (Release 9.0.2) to be merged in order to verify if it "just works" for other people. 

I will start work on documenting these changes now.

**Comment by logand22** [comment]
Docs Update:

Merged: https://github.com/gravitational/teleport-plugins/pull/473 which contained updates for README files in the different plugin directories

Descriptions in Quay now available for following repositories: 
* https://quay.io/repository/gravitational/access-plugin-email
* https://quay.io/repository/gravitational/access-plugin-mattermost
* https://quay.io/repository/gravitational/access-plugin-pagerduty
* https://quay.io/repository/gravitational/access-plugin-slack
* https://quay.io/repository/gravitational/access-plugin-jira
* https://quay.io/repository/gravitational/event-handler-plugin

**Comment by logand22** [comment]
With:
* https://github.com/gravitational/teleport/pull/11617
* https://github.com/gravitational/teleport/pull/11934

Documentation + backports for the above repos is added to goteleport.com in their corresponding guide sections.
