### ISSUE TITLE
terraform: support Alpine Linux

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport-plugins#447]
The makefile for the terraform provider explicitly sets `CGO_ENABLED=1`, which results in a build artifact that won't run on Alpine Linux containers (they lack glibc).

This prevents the use of GitLab CI with our terraform provider, as GitLab provides terraform [images based on Alpine](https://gitlab.com/gitlab-org/terraform-images).

If we don't actually require CGo in the provider, setting `CGO_ENABLED=0` might be all we need to do in order to support Alpine images.

Investigate whether the provider still functions with `CGO_ENABLED=0` and if an artifact compiled in this way will run in an Alpine container.

**Comment by zmb3** [comment]
This also seems to be an issue with [Atlantis](https://www.runatlantis.io/docs/deployment.html#architecture-overview), which runs Terraform on Alpine images.

**Comment by r0mant** [comment]
Thank you @marcoandredinis!

@Richard-Barrett We can cut a new release when the PR above merges. Should be able to do it this week.

**Comment by Richard-Barrett** [comment]
Thanks, @marcoandredinis, and @r0mant I know the customer trying to integrate Atlantis will be happy :D
