### ISSUE TITLE
Expand the email plugin to allow different recipients for different roles

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport-plugins#465]
Currently, the email plugin can only specify a single list of `recipients` that defines a list of recipients that will receive all access requests for all roles.

Feature request is to enable the email plugin to define different recipients for different requested roles, similar to the recent work done for the slack plugin and different channels https://github.com/gravitational/teleport-plugins/issues/411

This is important for organizations with multiple teams using Teleport that have different groups approving different roles.  Spamming them all is not scalable.

**Comment by r0mant** [comment]
@marcoandredinis As a part of this work, let's please also document the email plugin. Right now it's not documented at all unlike other plugins: https://goteleport.com/docs/enterprise/workflow/.
