### ISSUE TITLE
WASM Plugin: Generate README with directory

### ISSUE THREAD

**Issue by logand22** [gravitational/teleport-plugins#482]
Thoughts on generating README with basic instructions when running:

```code
$ teleport-plugin-framework new ~/teleport-plugin
```

could include the name of the directory that was created as title as well as the default `yarn` commands.

**Comment by gzigzigzeo** [comment]
That's a great idea. I'd just be great to make generated README DRY with the main repo's README to avoid double work on updates. I'll look into it once I finish my current task.
