### ISSUE TITLE
Terraform provider should support content, rather than filepaths, for auth

### ISSUE THREAD

**Issue by crielly** [gravitational/teleport-plugins#486]
Currently, teleport terraform provider expects file paths when using TLS auth:

```
provider "teleport" {
  addr         = "teleport.example.com:3025"
  cert_path    = "${path.module}/tf-auth-pki/client-cert.pem"
  key_path     = "${path.module}/tf-auth-pki/client-key.pem"
  root_ca_path = "${path.module}/tf-auth-pki/root-ca.pem"
}
```

This puts you in a situation where you must obviously already have the relevant files present on disk.

It would be preferable that the provider config accept content, rather than file paths - similar to how the TF kubernetes provider works.

This would provide users with the option of still dumping key/certs out to file and reading them via the file function, OR fetching them from a data source such as AWS SSM parameter store (my use case).

Notes:

One could argue here that the underlying issue is actually the lack of an AWS IAM authentication method for using the provider or otherwise using the teleport API. 

What I'm actually attempting to do is have two terraform states (though I'd be happy with one if it were possible) - one to deploy a teleport cluster, one to configure it.

My teleport auth servers have --bootstrap set, and in that yaml file, I define a terraform user and role for TF to use. The auth servers also have a systemd unit which periodically runs `tctl auth sign` and then uploads root_ca, cert, and key to SSM parameter store.

I'd like my teleport terraform provider to just read those values directly from SSM parameter store.

**Comment by marcoandredinis** [comment]
As of 9.0.4 we support base64 encoded strings for the provider auth configuration
```tf
provider "teleport" {
  addr           = "teleport.example.com:3025"
  cert_base64    = "<base64 encoded pem>"
  key_base64     = "<base64 encoded pem>"
  root_ca_base64 = "<base64 encoded pem>"
}

```

Would that work? (Sorry, if I'm misunderstanding your use case)
Feature PR: https://github.com/gravitational/teleport-plugins/pull/476
Docs PR: https://github.com/gravitational/teleport/pull/11764

**Comment by crielly** [comment]
@marcoandredinis That's fabulous. Should I close this issue? Not sure how y'all like to handle that lifecycle, but much appreciate the work as this makes my life a lot easier!

**Comment by marcoandredinis** [comment]
I'll close it
But feel free to close it next time, as you were the open that opened it
