### ISSUE TITLE
Consider adding `teleport-jirabot setup`that would automatically configure Jira instance

### ISSUE THREAD

**Issue by xnutsive** [gravitational/teleport-plugins#49]
FYI @benarent: Jira has an API that can register new webhooks, issue types, workflows, etc. That covers everything we need, and requires a few things to work: 
1. A valid user API token
2. Admin / owner privileges for said user. 
3. Valid Jira Server / Cloud address.

Right now we're requiring that our users setup their Jira instances themselves and providing a guide for it. We can simplify it by building a task that would automate the setup. 

Considering setup is a one-off thing, and there won't be a lot of folks installing the plugin early, I'd say we can start without it and see if we need it in the future, but just putting it out there so that we can discuss this. 

@marshall-lee researched the API and proposed the idea, I just typed it in.

**Comment by marshall-lee** [comment]
Note: it's still just an idea. There're some problems:

- Webhooks registered using API live only 30 days but they could be refreshed (`PUT /rest/api/3/webhook/refresh`).
- This API works only for [Connect apps](https://developer.atlassian.com/cloud/jira/platform/integrating-with-jira-cloud/#atlassian-connect).
- Webhook setup should be idempotent, i.e. it must not register the same webhook twice.

To achieve refresh logic + idempotency, we need to store `webhookIds` somewhere. It leads to introducing a persistent storage that we were trying to evade.

**Comment by marshall-lee** [comment]
We can try convert our app to a Connect app. But as far as I understand, connect apps don't work with JIRA Server installations, they're only for JIRA Cloud :(

**Comment by benarent** [comment]
I do like the idea for ease of use and setup, but as @marshall-lee mentioned it's JIRA Cloud only, and most RBAC customers use JIRA Server

**Comment by xnutsive** [comment]
I'll keep this open for a few more weeks — I think there's potential in this, and maybe once we gain more experience with Jira Server, we'd be able to automate parts of it's setup, too. Jira Server setup is 10x more complex and extensive than Cloud, and if we could do it automatically and guarantee it's integrity, that would be _very good_.
