### ISSUE TITLE
Support different JIRA projects?

### ISSUE THREAD

**Issue by marshall-lee** [gravitational/teleport-plugins#51]
For now, `jirabot` integrates only with a single jira project (board) specified in config file.
I thought it could be good to support multiple projects. Though I cannot come up with an idea how to route different access requests to their specific jira projects. For example, we could have a role -> project mapping but it's unclear what to do in a case when multiple roles being requested — create duplicate issues in all related projects?

**Comment by xnutsive** [comment]
Closing for now.
