### ISSUE TITLE
Jira Issue name should be more detailed

### ISSUE THREAD

**Issue by xnutsive** [gravitational/teleport-plugins#56]
When creating a Jira Issue, let's make it more self explanatory. Request IDs should also be included, but they're not readable on their own: 
<img width="309" alt="Screen Shot 2020-02-19 at 11 14 06 PM" src="https://user-images.githubusercontent.com/43633/74909678-ad2a6980-536d-11ea-90f8-1648e68abb5b.png">

Suggestion: 

{{Username}} requests roles {{roles}} on {{datetime of request}}. req id: {{request_id}}. 

/cc @benarent, @marshall-lee

**Comment by benarent** [comment]
+1, suggestion looks like a great improvement to this.
