### ISSUE TITLE
Clarify the error message when the Jira URL is invalid

### ISSUE THREAD

**Issue by xnutsive** [gravitational/teleport-plugins#60]
As of right now, if the Jira URL in the config is invalid (most likely cases: doesn't include a protocol name (`https://`), or includes `/jira` in the end), the plugin will fail with different error messages that are not readable. 

Missing http results in a segfault, and otherwise invalid URL just spits out the http response body, which would likely be a HTTP 404 page on the jira server (what we've seen with @benarent when we tested this a week ago). 

Suggestion: wrap the error message that `go-jira`spits out into our own error message struct with a clear explanation of what went wrong. Make explicit cases for missing protocol, having `/jira` in the end of a `*.attlassian.net` URL.

Linking to #59, I think this can be done first, and then we can call all the validation checks from `Run()` or on `NewBot()`.

**Comment by marshall-lee** [comment]
See https://github.com/gravitational/teleport-plugins/issues/59#issuecomment-594271148
