### ISSUE TITLE
Provide binaries for the terraform provider for other archs

### ISSUE THREAD

**Issue by marcelobartsch** [gravitational/teleport-plugins#605]
Hello,
Could be possible you provide binaries for the teleport terraform provider for other arch beside linux?

We are currently working into implement teleport with  terraform anmd having to compile the provider on each employee working in the project is painful and most people are working either in mac/intel or mac/M1 some in wintel machine too. also some of the CI runs on Linux/ARM so having those binaries provided by you would be a real saver for us.

Thanks.

**Comment by zmb3** [comment]
This is tracked in #539
