### ISSUE TITLE
[event-handler] Add an Issuer DN to generated X.509 certs

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport-plugins#606]
The X.509 parsing package in the Java standard library (`sun.security.x509`) requires that X.509 certs [include an Issuer DN field](https://github.com/openjdk-mirror/jdk7u-jdk/blob/f4d80957e89a19a29bb9f9807d2a28351ed7f7df/src/share/classes/sun/security/x509/X509CertInfo.java#L686-L690). Currently, the `event-handler` plugin issues certificates [without this field](https://github.com/gravitational/teleport-plugins/blob/90a961bd152a042a2fcbf50533e3ca5e50a29b94/event-handler/mtls_certs.go#L66-L89). This means that the `event-handler` plugin cannot establish a TLS handshake with log collection tools that use Java's `sun.security.x509` package, such as Logstash. We should add an Issuer DN to these certificates so we can expand the range of log management tools that Teleport users can integrate the `event-handler` plugin with.

**Comment by ptgott** [comment]
Hi @EdwardDowling, just checking whether there are any unexpected blockers here. If so, I can plan to document using the Fluentd exporter with the ELK stack (which would become the EFK stack), rather than the canonical ELK stack as originally planned. Thanks!

**Comment by EdwardDowling** [comment]
Sorry for the delay, I've made a PR for adding the issuer DN field. If we want to add options for the user to configure the fields I could add them to this PR.

**Comment by ptgott** [comment]
This looks good, thanks!

**Comment by r0mant** [comment]
@ptgott Do you have an environment set up by chance where we can validate that the fix Edward made [in this PR](https://github.com/gravitational/teleport-plugins/pull/640) fixes the issue?

**Comment by ptgott** [comment]
@r0mant I am writing/testing a guide to using the event handler with the Elastic Stack this week. I'll use an event handler build from this branch and post here when I've validated that this works.

**Comment by ptgott** [comment]
I ran into an issue with this, documented here: https://github.com/gravitational/teleport-plugins/pull/640#issuecomment-1233254971
