### ISSUE TITLE
New Plugin: Microsoft Teams

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#61]
During a demo yesterday, Microsoft showed off using Teams to create a SOC event. With Team growing we should consider creating a plugin for it. https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/building-an-app 

This is simply a placeholder, if a customer finds this. Please give it a 👍as a positive sign of intent.

[spec needed]

**Comment by xnutsive** [comment]
In terms of APIs: 

- Microsoft Teams supports [**Connectors**](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/what-are-webhooks-and-connectors) that essentially are bots who sit in a channel, and post a message when they receive an HTTP request. Creating a Connector means creating a special http endpoint that we'll then send JSON messages to. Similar to Slack bots.
- [**Adaptive interactive message cards**](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards), aka nicely formatted message with buttons, that can send an outgoing webhook when a button is pressed. Again, same as Slack.

**Comment by ciroiriarte** [comment]
Also interested in MS Teams integration, will this work for access approvals?

**Comment by Moulick** [comment]
Approvals in MS-Teams would be lovely

**Comment by thg-adamdean** [comment]
Also interested.

**Comment by pschisa** [comment]
closed by gravitational/teleport-plugins#617

**Comment by pschisa** [comment]
Re-opening as there is still some final testing to be completed and documentation to be produced
