### ISSUE TITLE
New Plugin: Pagerduty

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#62]
Create an '/incident' in PD https://v2.developer.pagerduty.com/docs/api-picker 

https://v2.developer.pagerduty.com/v2/docs/authentication 

Maybe create responser request, to approve workflow. ( need to explore more ) https://api-reference.pagerduty.com/#!/Incidents/post_incidents_id_responder_requests

**Comment by marshall-lee** [comment]
I did some research of the platform. The basic flow would be like this:

- Create a separate pagerduty service for access request incidents.
- When access request has been created in Teleport, create an incident in Pagerduty service as well. There's an rest api method for this: https://api-reference.pagerduty.com/#!/Incidents/post_incidents
- Looking at the incident, user is able to approve/reject access request. I think "custom incident actions" extension is good for this. Custom actions allow to call your custom endpoint when user press the action. Actions could be set up manually — https://api-reference.pagerduty.com/#!/Incidents/post_incidents, and probably it's also possible to set up them programmaticaly using extensions API — https://api-reference.pagerduty.com/#!/Extensions/post_extensions

**Unfortunately**, as far as i can see we cannot store metadata in incident's resource. In slackbot we store access request id as a block action `"value"`, in jira we store it in entity `"properties"`, but there's no similar thing in Pagerduty. So we have to choose one of the following things:

- Store incident_id -> request_id mapping in the file key-value storage (boltdb, sqlite)
- Implement a new GRPC API for *secondary key search* of access requests.

**Comment by fspmarshall** [comment]
@marshall-lee I'm not super familiar with pagerduty or its API, but it appears that `incident_key` is able to be an arbitrary string, and will be passed on as part of the payload generated by "custom incident actions".  I *think* you should be able to use the request ID as the `incident_key`, making it easy to load the correct data.

**Comment by marshall-lee** [comment]
@fspmarshall oops i overlooked it, perhaps it's a way to go!

**Comment by xnutsive** [comment]
- [ ] The text notification (sms) for the created incident says **Access request from %USERNAME%** — let's clarify and do **%username% requested %roles% on Teleport.**
