### ISSUE TITLE
Please update Jira Plugin to remove update permission

### ISSUE THREAD

**Issue by j-teleport** [gravitational/teleport-plugins#621]
On webpage, https://github.com/gravitational/teleport/discussions/9918

update method is deprecated and not recommended.

But with Jira Plugin, Jira will still need update permission if the customers want to approve access requests from Jira. The article linked is the recommendations for human users approving via the webui or CLI.

Could you please remove required update permission from Jira Plugin?

This request could avoid a user with both requester & approver role to approve his own request.

**Comment by r0mant** [comment]
@jingsun-teleport Can you update this ticket with more details? Right now it's not clear where do we need to remove the update permission and why.
