### ISSUE TITLE
terraform provider should recreate teleport_trusted_cluster if the role mapping changes

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport-plugins#622]
When trying to change the role mapping on an existing teleport_trusted_cluster terraform resource, the following error happens:

```
│   with teleport_trusted_cluster.root,
│   on trusted_cluster.tf line 5, in resource "teleport_trusted_cluster" "root":
│    5: resource "teleport_trusted_cluster" "root" {
│ 
│ can not update role_map for existing leaf cluster, delete and re-create
│ this leaf cluster with updated role_map
```

The terraform provider should handle the required delete and re-create on its own rather than erroring out and asking the user to do it.

gz#6135

**Comment by r0mant** [comment]
We won't update our Terraform module to recreate trusted clusters in this scenario. Instead, we'll implement ability to update trusted cluster role mapping without having to recreate the trusted cluster relationship: https://github.com/gravitational/teleport/issues/10568.

Going to close this issue, please subscribe to the Teleport one linked above for updates instead.
