### ISSUE TITLE
Jira Server basic auth support

### ISSUE THREAD

**Issue by xnutsive** [gravitational/teleport-plugins#63]
Add support for basic authentication with Jira Server, since it doesn't recognize API token auth. 

For this to work: 

### Add user and password to the config file

In `teleport-jirabot.toml [jira]` section, add `password` setting. The password setting can be provided along with the API token setting, the next section describes which one of them should be used. 

### Bot logic: choosing auth strategy 

The bot should dynamically figure out what it's working with (Cloud vs Server) and choose the right auth strategy: 

- Look at the Jira URL. If it has atlassian.com in it — it's a Jira Cloud instance. Then check if the API token is provided. If it is — all good, proceed. If there's no token — error out, and ask the user to use API token to authenticated. 
- If the Jira URL doesn't have atlassian.com in it, consider it a Jira Server URL. In this case, try using the password setting. If there's no password in the config — error out. 

### Update the readme 

Jira Plugin installation instructions should be clear on the fact that it's probably best if a special service user is created for the bot, and their capabilities limited to managing just the permissions board, to limit any exposure if the password is stolen.

**Comment by marshall-lee** [comment]
For jira cloud we use basic auth too — the token is used instead of password. I don't get what's different for jira server.

**Comment by xnutsive** [comment]
I'm not sure about renaming the config option yet, want to hear from clients first. If the current config setup doesn't confuse anyone — than it doesn't require any changes. I'll close this issue though, since Jira Server authentication actually works fine now.
