### ISSUE TITLE
[Jira plugin] Remove the `issue_type` config field

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport-plugins#635]
The only use of the `IssueType` struct, in `Jira.CreateIssue`, hardcodes the `Name` as `"Task"`:

```
 % grep -Rn "&IssueType" access/jira
access/jira/client.go:202:                      Type:        &IssueType{Name: "Task"},
```

There's no need to expose an `issue_type` config option to the user. We can remove this to avoid confusion for anyone browsing the Jira plugin source.

**Comment by marcoandredinis** [comment]
We can either remove it or allow for a couple of issue types
I would start with `Task,Story`

Besides those I don't see a real use case for controlling access
Even `Story` seems to be a long shot but no I'm not going to judge how people use Jira :sweat_smile:
