### ISSUE TITLE
Create a new terraform-provider-teleport command that would iterate over all supported resources and import them into terraform state

### ISSUE THREAD

**Issue by ArunNadda** [gravitational/teleport-plugins#643]
terraform-provider-teleport shall have a new command, which can be used to import manually created resources to terraform state. In addition to this it should also create a `tf` file for these resources.

### What problem does this solve?
It will allow already create resources in teleport to be imported to terraform.

### If a workaround exists, please include it.
Resources can be imported currently, but all import resource details should be created manually, which is error prone and time consuming.

**Comment by hugoShaka** [comment]
From what I understand, This is not a feature request for the provider but for Terraform itself.
It seems Terraform devs did something similar [with import blocks](https://developer.hashicorp.com/terraform/language/import). A combination of `tctl get <resource>` and import blocks should allow one to import all resources at once.

I'll close this as this is a Terraform feature request.
