### ISSUE TITLE
Ability to enable auto-approval in PagerDuty helm chart.

### ISSUE THREAD

**Issue by ArunNadda** [gravitational/teleport-plugins#658]
The Helm Chart for PagerDuty currently lacks the ability to enable auto-approval. We should provide this option in helm-chart.

**Comment by hugoShaka** [comment]
Hello @ArunNadda, I double checked in the documentation and the code: auto-approval does not seem gated behind any setting. As far as I know the Helm chart behaves exactly as the bare plugin. 

Can you explain what you were trying to achieve and what error you encountered?

**Comment by ArunNadda** [comment]
hmmm, did autoapproval behaviour change recently?  I remember reading docs that it required `auto_approve = true` in `toml` file for PD 🤔 

As its still present in v9 docs. ref: https://goteleport.com/docs/ver/9.0/enterprise/workflow/ssh-approval-pagerduty/#on-call-auto-approval

```
# Example teleport-pagerduty.toml snippet
#...
[pagerduty]
api_key = "key"               # PagerDuty API Key
user_email = "me@example.com" # PagerDuty bot user email (Could be admin email)
service_id = "PIJ90N7"        # PagerDuty service id
auto_approve = true           # Auto approve
```

With current behaviour, helm chart should also work. Thanks

**Comment by hugoShaka** [comment]
OK, I investigated deeper and you're right" the behaviour you describe existed at some point: https://github.com/gravitational/teleport-plugins/commit/c79aa23ba219a46a92548f74c7f92a24af37bc75#diff-ed07f7a2e42fae35318913610f85c5089720bec63982ca157eeaf94c0f6b4b4e

[This was revamped in Teleport v7](https://github.com/gravitational/teleport-plugins/pull/266), it seems the documentation fix was made recently and not backported enough.

I will close the issue and fix the docs, thanks for the report :)
