### ISSUE TITLE
Extend Workflows API to include integration for Mattermost

### ISSUE THREAD

**Issue by aelkugia** [gravitational/teleport-plugins#66]
Currently integrations are being worked on for Jira and Slack to provide approval workflows.

Submitting ticket from some customer feedback on looking for an integration for Mattermost.

**Comment by marshall-lee** [comment]
Mattermost has a great official Go client library, it'd be fun to integrate with.

Sample go bot: https://github.com/mattermost/mattermost-bot-sample-golang. Today I got it up & running locally with slight modifications (the example uses user&password authentication but i created a _bot account_ with authentication via token).

Workflow would be pretty much the same as in Slack. For instance, Mattermost supports interactive messages too: https://docs.mattermost.com/developer/interactive-messages.html.
