### ISSUE TITLE
Mattermost Bot config checks at startup

### ISSUE THREAD

**Issue by xnutsive** [gravitational/teleport-plugins#69]
I've been testing mattermost bot, will commit the docs in a few minutes! A few things I've noticed along the way: 

- [ ] Mattermostbot doesn't log “starting a request watcher” or "checking teleport auth version" — all the other plugins do. Bug?
- [x] There's no config check at startup. Specifically, the bot will start and not error out even if the config doesn't have `mattermost:url`, `webhook:base-url`. 
- [x] There's no permissions check at startup. If the bot is not in the team that's configured, it'll only fail when it tries to post a message to Mattermost. 
- [x] In the config, team name and channel name should be in a specific format (i.e. `teleport-team` instead of `Teleport Team`). I think the health check will solve this problem, just make sure to write a clear error message in case the config entry for the team or channel name has spaces — they should be dashes instead, but that's not obvious.

**Comment by marshall-lee** [comment]
> Mattermostbot doesn't log “starting a request watcher” or "checking teleport auth version" — all the other plugins do. Bug?

I changed a severity of these log messages in all the plugins, so you can only see them with `-d` option. In fact, they're just debug messages and should not be logged in normal scenario.
