### ISSUE TITLE
 Incorrect documentation for Terraform teleport_role resource 

### ISSUE THREAD

**Issue by Nuru** [gravitational/teleport-plugins#699]
The Terraform [teleport_role documentation](https://goteleport.com/docs/reference/terraform-provider/?scope=enterprise#teleport_role) documents `app_labels` like this:

![image](https://user-images.githubusercontent.com/2793313/201417778-fd386ea5-ae3f-4730-8947-94557a48177e.png)

This means (to me, anyway) that you should set `app_labels` like this:

```hcl
app_labels = [{
  key = "example"
  values = ["a", "b"]
},
{ 
  key = "other"
  values = ["1", "2"]
}]
```

However, in `provider terraform.releases.teleport.dev/gravitational/teleport v11.0.1`, this is far from how you actually need to set the field. It appears the correct syntax for the above settings is:

```hcl
app_labels = {
  key = ["example"]
  values = ["a", "b"]
}
app_labels = { 
  key = ["other"]
  values = ["1", "2"]
}
```

**except that does not work** because this is inside a map and the second `app_labels` key overwrites the first. 

This applies to the other `*_labels` settings as well. 

Note that `rules` is also documented to be a `set`, but that is correct. This works as expected:

```hcl
rules = [{
  resources = ["*"]
  verbs     = ["*"]
}]
```

**Comment by marcoandredinis** [comment]
Can you please try the following syntax?
```tf
      node_labels = {
        example    = ["1", "2"]
        other    = ["1", "2"]
      }
```

**Comment by Nuru** [comment]
Alright, that works, I see what the docs were trying to say now. An example in the docs would have cleared up the confusion.
