### ISSUE TITLE
Documentation for Slack Bot

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#7]
We often start with a documentation first approach to product development. This issue is to track the high level docs required for our end users. 

- [ ] How to setup `Teleport Plugin` Binary
- [ ] How to export cert & roles to approve roles
- [ ] How to obtain the correct API keys & OAuth tokens from Slack. 
- [ ] Approval Workflow. How to setup the roles & integrate with your team.

**Comment by benarent** [comment]
I have a WIP for this https://gist.github.com/benarent/da80e3167ed1e997818ed37d355ad422#installing

**Comment by xnutsive** [comment]
I've updated the doc a bit in a fork. Setup everything without any issues. https://gist.github.com/xnutsive/34b0f2c472f9657825c1a14b04eb73e1

I'll test the systemd part, and if everything's ready — we can do a screencast and start rolling this out.

**Comment by xnutsive** [comment]
What do you mean re: approval workflows? 

One thing I myself am not sure about is how can a user request a role? There's `tctl request create`, but my understanding was that `tctl` is an admin tool, not an enduser tool?

**Comment by benarent** [comment]
See https://gravitational.com/teleport/docs/enterprise/#setup

It uses `tsh` 

```
e.g. $ tsh login  --request-roles=dba
Seeking request approval... (id: bc8ca931-fec9-4b15-9a6f-20c13c5641a9)
```

**Comment by xnutsive** [comment]
Ah, my bad. Thanks for pointing this out!

**Comment by benarent** [comment]
Closing as moving this to Teleport Docs Repo https://github.com/gravitational/teleport/pull/3699
