### ISSUE TITLE
Unable to specify multiple *_labels filters in teleport_role Terraform resource

### ISSUE THREAD

**Issue by Nuru** [gravitational/teleport-plugins#700]
When creating a role (and probably also a user) via Terraform, there is no way to specify multiple configurations of any of the labels. `spec.app_labels` should take a list of maps, but it only takes a single map. The same is true with other `*_labels` fields. 

# References
- #699

**Comment by marcoandredinis** [comment]
Reference docs is not clear
Should be used like this

```tf
      node_labels = {
        example    = ["1", "2"]
        other    = ["1", "2"]
      }
```

I'll create a PR to improve ref docs

**Comment by Nuru** [comment]
@marcoandredinis Thank you. 

While you are at it, you might create a PR or at least a task to update the Terraform docs in general. They are missing a lot. For example:
- `teleport_provision_token` [`spec`](https://goteleport.com/docs/reference/terraform-provider/?scope=enterprise#teleport_provision_token) has a more than a "single field: `roles`" (it has `join_method` and `allow` and `aws_iid_ttl`).  I was very confused by `roles` because I thought it was referring to `teleport_role` after it refused to accept "node" as a role. So (a) "role" means 2 different things in Teleport documentation, to the Terraform docs should disambiguate which kind of role it is referring to, and (b) for the Terraform resource, and nowhere else, role has to be capitalized, "Node" not "node", and this should be called out. 
- [`teleport_role`](https://goteleport.com/docs/reference/terraform-provider/?scope=enterprise#teleport_role) `spec.allow` and `spec.deny` accept a currently undocumented field of `windows_desktop_labels`. 

There are probably more examples, those are just the ones I have come up against in the past week.
