### ISSUE TITLE
The new `identity_file_base64` doesn't decode base64 properly

### ISSUE THREAD

**Issue by tonedefdev** [gravitational/teleport-plugins#702]
I was excited to see this issue was addressed as I needed it to automate our use case, so I got around to testing it after it was released. Unfortunately, I'm seeing the provider return this error:

```text
│ Error: Failed to decode Identity file using base 64
│ 
│   with provider["terraform.releases.teleport.dev/gravitational/teleport"],
│   on test.tf line 20, in provider "teleport":
│   20: provider "teleport" {
│ 
│ Error when trying to decode: illegal base64 data at input byte 9854
```

I can use `base64 -d` on my Mac to decode the same base64 string without any errors, so I'm not too sure why the provider is having difficulties with it.

**Comment by tonedefdev** [comment]
Actually, I figured out the issue. When I was base64 encoding it was adding `=` to the end of the string and the decoded didn't like this. Once I removed it, it worked.

**Comment by programmerq** [comment]
I would consider this to be a bug in the provider. The `=` at the end of the base64 encoding is padding, and _most_ base64 encoders utilize padding.

The new `identity_file_base64` option is utilizing [base64.RawStdEncoding](https://github.com/gravitational/teleport-plugins/blob/v11.0.3/terraform/provider/provider.go#L291]

But the previously existing base64 provider configurations are using [base64.StdEncoding](https://github.com/gravitational/teleport-plugins/blob/master/terraform/provider/provider.go#L436-L453)

The main difference between RawStdEncoding and StdEncoding seems to be whether the padding is expected or not: https://pkg.go.dev/encoding/base64#pkg-variables

I would expect padding to be present in nearly every conceivable situation. I would argue that the code should be changed to use base64.StdEncoding across the board.
