### ISSUE TITLE
Publish darwin_arm64 Terraform provider

### ISSUE THREAD

**Issue by mcantinqc** [gravitational/teleport-plugins#706]
The Terraform provider for Teleport is already build and publish on terraform.releases.teleport.dev/gravitational/teleport, but it's not build for darwin_arm64.

I follow steps from https://github.com/gravitational/teleport/discussions/10274, that work, but that could be easier to have the provider already build for each plateform.

**Comment by zmb3** [comment]
Duplicate of #539
