### ISSUE TITLE
Pagerduty: improve incident title and details

### ISSUE THREAD

**Issue by xnutsive** [gravitational/teleport-plugins#71]
In Pagerduty integration, incident title and text need some work. 

**Incident title / text notification**
The text notification (sms) for the created incident says `Access request from %USERNAME%`. 

Let's clarify it and do `%username% requested %roles% on Teleport` instead. 

**Incident Details**
They're missing, right now it says `TODO ebc197dd-24bc-4bc8-9002-a6c95956024f` — I assume the hex string is `request_id`. 

Should be something like: 

> %username% requested permissions for roles %roles% on Teleport at %time%. To approve or deny the request, please use Special Actions on this incident.

**Comment by marshall-lee** [comment]
I won't include role list in the incident title, it's redundant since incident details will include it anyway, and also full role list could be cumbersome.
