### ISSUE TITLE
Review integration and functional tests for plugins.

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#82]
To support long term maintainability of the Teleport plugins we need to have as much test help as possible. 

- [ ] Review Integration tests
- [ ] Provide options for functional tests.

Nate: 
- [ ] Add race condition detection to tests.

**Comment by xnutsive** [comment]
@marshall-lee, I know you refactored quite a few things before your time off — is this one addressed, or is there anything else you'd add to the tests we currently have?

**Comment by xnutsive** [comment]
@marshall-lee @webvictim do you guys want to chat more about integration tests, or are you happy with them for now and we should close this?

**Comment by xnutsive** [comment]
Just had a chat with @marshall-lee — turns out we're still working on race condition detection, will push updates later this week, starting with the pagerduty plugin. 

So, still working on this one.

**Comment by marshall-lee** [comment]
Closed as stale
