### ISSUE TITLE
[Pagerduty plugin] 13.2.2 doesn't set APIEndpoint 

### ISSUE THREAD

**Issue by espadolini** [gravitational/teleport-plugins#868]
After merging gravitational/teleport#28883 nothing sets the `PagerdutyConfig.APIEndpoint` field anymore; it used to be left empty on the teleport-plugins side and then filled in on the teleport side, but now it's just left blank, so starting up the plugin fails with a `*url.Error Get "/abilities": unsupported protocol scheme ""`.

**Comment by r0mant** [comment]
I think this was fixed, right @tcsc?
