### ISSUE TITLE
Terraform reference docs use number rather than enum for `create_host_user_mode`

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport-plugins#878]
The auto-generated Terraform reference says this field is a `number`

https://github.com/gravitational/teleport-plugins/blob/f95374209cf838d07b4bc65f48cf40004be2c6b3/terraform/reference.mdx#L1557

However in the docs (https://goteleport.com/docs/reference/resources/#role) it says you can use either `keep`, `drop` or `off`

My guess is that this is related to the proto definition: https://github.com/gravitational/teleport/blob/8c25629119eee8781c2418f506e36f94978e526d/api/proto/teleport/legacy/types/types.proto#L2402-L2413

```
const (
	CreateHostUserMode_HOST_USER_MODE_UNSPECIFIED CreateHostUserMode = 0
	// HOST_USER_MODE_OFF disables host user creation.
	CreateHostUserMode_HOST_USER_MODE_OFF CreateHostUserMode = 1
	// HOST_USER_MODE_DROP enables host user creation and deletes users at session end.
	CreateHostUserMode_HOST_USER_MODE_DROP CreateHostUserMode = 2
	// HOST_USER_MODE_KEEP enables host user creation and leaves users behind at session end.
	CreateHostUserMode_HOST_USER_MODE_KEEP CreateHostUserMode = 3
)
```

**Comment by hugoShaka** [comment]
Should be fixed by specifying the number-> value mapping in the godoc
