### ISSUE TITLE
We should be able to run these plugins without needing to be root for security

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#93]
It looks like we require plugins to run as root as it has to read the auth.crt, we should run these plugins without requiring root. 

```
teleport5auth ~: teleport-pagerduty start
INFO   Starting Teleport Access PagerDuty extension 0.1.0-alpha.1:teleport-jira-v0.1.0-alpha.1-0-gebfacdf pagerduty/main.go:124
ERRO   Terminating... error:open /var/lib/teleport/plugins/mattermost/auth.crt: permission denied utils/bail.go:17
teleport5auth ~: sudo teleport-pagerduty start
```

**Comment by marshall-lee** [comment]
@benarent 

Plugins will run without `sudo` with proper `chmod`/`chown` on `/var/lib/teleport/plugins/mattermost/` directory. 
Also the path itself can be configured to something `/home/user/teleport-mattermost` if the user wishes so.

**Comment by xnutsive** [comment]
+1. As long as we store data in `/var/lib/teleport/plugins/*` — we'll some privileged access. It makes sense to use / advise to use different users from users running Teleport itself, to isolate Teleport data in a single host environment.

**Comment by xnutsive** [comment]
Self-assigned to keep track of this. @benarent, please let me know if you think this needs product changes, or more of docs changes to reflect how to run without root privileges?
