### ISSUE TITLE
Access plugin containers are broken in v14.0.1

### ISSUE THREAD

**Issue by espadolini** [gravitational/teleport-plugins#935]
After #928 the containers are based on distroless-static, but the binaries we put inside them are still built with CGO, resulting in a (confusing) `exec: /usr/local/bin/teleport-plugin: not found` error because the `/lib64/ld-linux-x86-64.so.2` interpreter is not in the image.

We should revert #928 or ensure that the build is indeed static.

**Comment by marcoandredinis** [comment]
We should be able to build the binaries without CGO.
Either approach should work
