### ISSUE TITLE
Upgrade `terraform-provider-framework` to greater than `1.0.0`

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport-plugins#964]
We're on a fairly old version and it's blocking other tickets, such as generating a Pulumi compatible provider from the Terraform provider: https://github.com/gravitational/teleport/issues/14584

**Comment by marcoandredinis** [comment]
I think this is a duplicate of
https://github.com/gravitational/teleport-plugins/issues/684

**Comment by strideynet** [comment]
Duplicate of #684 

Hah, apologies @marcoandredinis - I searched "upgrade" rather than "bump"
