### ISSUE TITLE
Terraform Provider should support for v7 Role spec

### ISSUE THREAD

**Issue by darend** [gravitational/teleport-plugins#982]
## Expected Behavior

Unable to create roles that use the v7 spec. 

For example the [v7 role spec](https://goteleport.com/docs/access-controls/reference/#role-versions) expanded RBAC support for Kubernetes Resources. This example should not cause an error:

```tf
resource "teleport_role" "app_readonly" {
  metadata = {
    name        = "Readonly"
  }
  spec = {
        {
          kind      = "*"
          namespace = "app"
          name      = "*"
          verbs     = ["get", "list", "watch"]
        }
      ]
  }
}
```

## Current Behavior

Applying the resource above results in this error

```tf
resource "teleport_role" "readonly" {

KubernetesResource "*" is not supported in role version "v6". Upgrade the role version to "v7"
```

**Comment by wadells** [comment]
This was fixed by https://github.com/gravitational/teleport-plugins/pull/925
